### ISSUE TITLE
[FEA] cuSignal restructuring to match other RAPIDS projects

### ISSUE THREAD

**Issue by seunghwak** [rapidsai/cusignal#10]
I have listed tasks to match cuSignal's structure to other RAPIDS projects (e.g. cuDF, cuGraph, cuML, and cuSpatial). We may not need to work on all these tasks right now, and I created this document to collect feedback.

- [ ] Create the /python directory: RAPIDS projects have the /python & /cpp directories. We can create the /python directory now to follow this structure or leave this as future work as cuSignal is currently python only and we may not add any C++ code in the foreseeable future.
- [ ] Run flake8 on python files and fix formatting errors and add setup.cfg file specifying flake8 configurations: RAPIDS projects enforce the PEP 8 compatibility through flake8.
- [ ] Add build.sh: RAPIDS projects have build.sh. This may not be necessary right at this moment as cuSignal is python only and really there is nothing to build. We may create the file as a placeholder or leave this as future work.
- [ ] Move notebook files to https://github.com/rapidsai/notebooks: RAPIDS notebook files are managed in the notebooks repo. We may move notebook files now or leave this as future work.
- [ ] Add print_env.sh: RAPIDS projects have print_env.sh file to print user environments/configurations to help bug reporting.
- [ ] Add MANIFEST.in, versioneer.py, and _version.py.
- [ ] Update setup.py to mimic other RAPIDS projects.
- [ ] Create sub-directories for python files: RAPIDS subgroup python files but we may better leave this as future work as cuSignal currently has only little more than 10 files.
- [ ] Add license statements
- [ ] Avoid using import * in \_\_init\_\_.py files

**Comment by awthomp** [comment]
I think this all sounds good, @seunghwak. I'd like to add:

- [ ] Generate documentation to link to the RAPIDS docs

Additionally, my preference would be for keeping the notebooks in this directory. I'm happy to have more "end-to-end" or application specific ones in the RAPIDS notebooks repo, but I'd want to ensure that folks who stumble on cuSignal have a quick on-ramp to the library in as few clicks as possible.

**Comment by awthomp** [comment]
Closed with https://github.com/rapidsai/cusignal/pull/11
