### ISSUE TITLE
[FEA] updating upfirdn to match upcoming SciPy 1.5 release

### ISSUE THREAD

**Issue by grlee77** [rapidsai/cusignal#102]
**Is your feature request related to a problem? Please describe.**

I just wanted to make the cuSignal devs aware that there will be a small change to the signal output length of `upfirdn` in the upcoming SciPy 1.5 release. (In some cases the returned signal will be slightly shorter).

**Describe the solution you'd like**
Make changes to the output length as in scipy/scipy#12159

**Describe alternatives you've considered**

**Additional context**
A related issue on SciPy is scipy/scipy#9844.

**Comment by awthomp** [comment]
Thanks for the heads up. @grlee77 !

**Comment by mnicely** [comment]
Thanks @grlee77! You da man!
