### ISSUE TITLE
[FEA] Update PyTest and PyTest-Benchmark Modules/Classes to Match Code Reorg

### ISSUE THREAD

**Issue by awthomp** [rapidsai/cusignal#107]
The current pytest/pytest-benchmark scripts assume the legacy (cusignal <= 0.13) organization. Rather than:

```
test_signaltools.py
test_spectral.py 
test_waveforms.py
test_wavelets.py
test_windows.py
```

We should include:

- [ ] test_convolution.py
- [ ] test_spectral.py
- [ ] test_filtering.py
- [ ] test_filter_design.py
- [ ] test_spectral_analysis.py
- [ ] test_waveforms.py
- [ ] test_wavelets.py
- [ ] test_windows.py
- [ ] test_bsplines.py
- [ ] test_acoustics.py (although this will add an additional dependency on cuSignal. Maybe not relevant?)

The same functionality should extend to the benchmarks:

- [ ] bench_convolution.py
- [ ] bench_spectral.py
- [ ] bench_filtering.py
- [ ] bench_filter_design.py
- [ ] bench_spectral_analysis.py
- [ ] bench_waveforms.py
- [ ] bench_wavelets.py
- [ ] bench_windows.py
- [ ] bench_bsplines.py
- [ ] bench_acoustics.py (although this will add an additional dependency on cuSignal. Maybe not relevant?)

**Comment by mnicely** [comment]
I believe `*_spectral.py` should be moved to `*_spectral_analysis.py` versus having both.
