### ISSUE TITLE
[BUG] Rename "master" branch.

### ISSUE THREAD

**Issue by cwharris** [rapidsai/cusignal#135]
Decades from now, will history students wonder why an entire industry decided to rename a core part of its infrastructure, or will they wonder why it was named that way to begin with?

Let's rename the "master" branch.

rapidsai/cudf#5560

**Comment by awthomp** [comment]
Agree. I want to fix this ASAP. While cuSignal follows the RAPIDS ops team in terms of SW management, and the default branch is pegged as `branch-XXX`, I'd like to see all mention of `master` removed. I'll default to how OPs goes about the change (e.g. we could rename to `default`).

**Comment by mike-wendt** [comment]
As mentioned in rapidsai/cudf#5560 there is a coordinated effort for this that is still in progress. Once approved a new issue with steps for each repo will be created here and the necessary PRs for the transition in the next few weeks.
