### ISSUE TITLE
[BUG] Bug/Error in resample_poly for large resample factors and large input sizes

### ISSUE THREAD

**Issue by gtg740x** [rapidsai/cusignal#137]
**Describe the bug**
Resampling a large array with a large up/down factor results in periodic sections of samples with value of zero with resample_poly(..., use_numba=False) or a phase discontinuity with resample_poly(..., use_numba=True). The periodicity is the same for both issues. 

Run the example code below to see the result when compared to scipy.signal.resample_poly. 

**Steps/Code to reproduce bug**
Sample Code:
```python
import numpy as np
import cusignal
import scipy
from matplotlib import pyplot as plt
from cusignal import resample_poly as cusignal_resample_poly
from scipy.signal import resample_poly as scipy_resample_poly

print('cusignal:', cusignal.__version__)
print('scipy:', scipy.__version__)

n = int(25e6)
x = np.random.randn(n) + 1j*np.random.randn(n)
x += 2*np.exp(1j*2*np.pi*0.1*np.arange(n))

y_cusignal = cusignal_resample_poly(x, 400, 1333, use_numba=False)
y_cusignal_use_numba_true = cusignal_resample_poly(x, 400, 1333, use_numba=True)
y_scipy = scipy_resample_poly(x, 400, 1333)

plt.figure(figsize=(6, 10))
plt.subplot(511)
plt.plot(np.abs(x))
plt.title('Original Data')
plt.subplot(512)
plt.plot(np.abs(y_scipy))
plt.title('Scipy Resample')
plt.subplot(513)
plt.plot(np.abs(y_cusignal.get()))
plt.title('Cusignal Resample')
plt.subplot(514)
plt.plot(np.abs(y_cusignal_use_numba_true.get()))
plt.title('Cusignal Resample - use_numba=True')
plt.subplot(515)
plt.plot(np.abs(y_scipy - y_cusignal_use_numba_true.get()))
plt.title('Phase Error: np.abs(y_scipy - y_cusignal_use_numba_true)')
plt.tight_layout()
plt.show()
```
**Expected behavior**
Expected the output to be the same as scipy.signal within precision limits.

**Environment details (please complete the following information):**
 - Environment location: [Bare-metal, Docker, Cloud(specify cloud provider)]
 - Method of cuSignal install: [conda, Docker, or from source]
   - If method of install is [Docker], provide `docker pull` & `docker run` commands used

System GPU: V100 32GB
Driver: 418.67
Base docker image: tensorflow/tensorflow:2.1.0-gpu-py3
Method of installing inside docker:
```
 RUN pip install cupy-cuda101 numba && \
    git clone https://github.com/rapidsai/cusignal && \
    cd cusignal/python && python setup.py install
```

**Comment by gtg740x** [comment]
I also re-tested this with the following conda environment on my local laptop:

(P5000, Ubuntu 16.04, 418.87.01)

conda create -n cusignal -c rapidsai -c nvidia -c numba -c conda-forge cusignal=0.14 python=3.6 cudatoolkit=10.1
conda install ipython jupyter matplotlib

This resulted in the same output as the server:

[Sample Output Plot]https://i.imgur.com/64Q5kFF.png)

**Comment by gtg740x** [comment]
And just to narrow down the issue, I factored out the resample to two stages of up 20, down 31 and up 20, down 43, and then all three methods have consistent results:

```python
import numpy as np
import cusignal
import scipy
from matplotlib import pyplot as plt
from cusignal import resample_poly as cusignal_resample_poly
from scipy.signal import resample_poly as scipy_resample_poly

print('cusignal:', cusignal.__version__)
print('scipy:', scipy.__version__)

n = int(25e6)
x = np.random.randn(n) + 1j*np.random.randn(n)
x += 2*np.exp(1j*2*np.pi*0.1*np.arange(n))

# p, q = 400, 1333
p, q = 20, 31
y_cusignal = cusignal_resample_poly(x, p, q, use_numba=False)
y_cusignal_use_numba_true = cusignal_resample_poly(x, p, q, use_numba=True)
y_scipy = scipy_resample_poly(x, p, q)

p, q = 20, 43
y_cusignal = cusignal_resample_poly(y_cusignal, p, q, use_numba=False)
y_cusignal_use_numba_true = cusignal_resample_poly(y_cusignal_use_numba_true, p, q, use_numba=True)
y_scipy = scipy_resample_poly(y_scipy, p, q)

plt.figure(figsize=(6, 10))
plt.subplot(511)
plt.plot(np.abs(x))
plt.title('Original Data')
plt.subplot(512)
plt.plot(np.abs(y_scipy))
plt.title('Scipy Resample')
plt.subplot(513)
plt.plot(np.abs(y_cusignal.get()))
plt.title('Cusignal Resample')
plt.subplot(514)
plt.plot(np.abs(y_cusignal_use_numba_true.get()))
plt.title('Cusignal Resample - use_numba=True')
plt.subplot(515)
plt.plot(np.abs(y_scipy - y_cusignal_use_numba_true.get()))
plt.title('Phase Error: np.abs(y_scipy - y_cusignal_use_numba_true)')
plt.tight_layout()
plt.show()
```

**Comment by awthomp** [comment]
Thanks for submitting the issue, @gtg740x. I've confirmed this bug on my system. 

As an aside, rather than plotting results, I'm using:

```python
from cusignal.test.utils import array_equal
array_equal(cp.asnumpy(y_cusignal), y_scipy)
```

@mnicely -- I know your schedule is a bit wonky this week, so I'll take a first pass and see if I can find where the bug is. I'm assuming we have an issue in `upfirdn`. A few key points:
* Even though we've deprecated Numba CUDA in 0.15, I had @gtg740x check the correctness between Numba CUDA and Raw CuPy CUDA; both fail.
* There's nothing wrong with the large filter and upsample/downsample sizes that @gtg740x used, as you can see a 2-stepped resample poly produces the correct results.

**Comment by mnicely** [comment]
@gtg740x It looks like the issue was dealing with an overflow which I did not expect. I believe it has been fixed #138 .

Do you mind retesting with the PR branch or once it has been pushed to 0.15 nightly?

**Comment by awthomp** [comment]
And just to be explicit, since we're pushing this change into 0.15 (and available with the cusignal nightlies), the `use_numba` option has been deprecated from the API.

You can either build from source: [instructions here](https://github.com/rapidsai/cusignal#source-linux-os) or grab the conda nightly tomorrow morning via:

`conda install -c rapidsai-nightly -c nvidia -c numba -c conda-forge cusignal`

**Comment by gtg740x** [comment]
@mnicely - I pulled your PR branch and everything looks good on my end. Really appreciate the fast response time on this! Thanks
