### ISSUE TITLE
[FEA] Examine CuPy Pre-Release 8.0.0 FFT Enhancements and Profile Manual FFT Plan Creation

### ISSUE THREAD

**Issue by awthomp** [rapidsai/cusignal#14]
There are currently two different CuPy functions to perform an FFT which tend to be used interchangeably in cuSignal.
1. `cupy.fft.fft`: [docs](https://docs-cupy.chainer.org/en/stable/reference/generated/cupy.fft.fft.html#cupy.fft.fft)
2. `cupyx.scipy.fftpack.fft`: [docs](https://docs-cupy.chainer.org/en/stable/reference/generated/cupyx.scipy.fftpack.fft.html)

We need to
- [ ] Better understand the performance implications between these two calls
- [ ] Make use of the ability to create an FFT plan and pass it to `cupyx.scipy.fftpack.fft` for additional performance where applicable 

Notably, when a user invokes `cupy.fft.fft` for the first time, much of the compute time is spent creating the FFT plan and memory allocation. If you know the sizes/direction of your FFT, you can do this once during pre-processing steps and pass in the desired FFT plan via `cupyx.scipy.fftpack.fft`. See below for an example:

**cupy.fft.fft only: FFT plan automatically created before FFT execution**
```python
signal = cupy.random.rand(100_000_000)
# creates FFT plan and executes FFT
fft_signal = cupy.fft.fft(signal)
```

**cupyx.scipy.fftpack.fft: Manually create FFT plan and execute FFT**
```python
signal = cupy.random.rand(100_000_000)
# manually create FFT plan
plan = cupyx.scipy.fftpack.get_fft_plan(signal, axis)
# perform FFT with generated plan
fft_signal = cupyx.scipy.fftpack.fft(signal, plan=plan)
```

**Comment by awthomp** [comment]
Changing title to update the issue.

One new FFT feature has been added in the 8.0.0 pre-release of CuPy, and that's the ability to disable n-dimensional FFT planning. This can potentially accelerate nD FFTs at the cost of physically taking more GPU memory. I'd like to analyze use of this in cuSignal in addition to the FFT differences in the original issue submission.

https://docs-cupy.chainer.org/en/stable/reference/generated/cupyx.scipy.fftpack.get_fft_plan.html#cupyx.scipy.fftpack.get_fft_plan

**Comment by leofang** [comment]
For the original issue: The underlying implementation of all 3 FFT variants in CuPy is the same, and so you can use them interchangeably to a large extent (at least for C2C) like this:
```python
in = ...
plan = cupyx.scipy.fft.get_fft_plan(in, ...)  # note get_fft_plan is also exposed to cupyx.scipy.fft
with plan:
    out = cupy.fft.fft(in, ...)
    # or
    out = cupyx.scipy.fftpack.fft(in, ...)
    # or
    out = cupyx.scipy.fft.fft(in, ...)
```

For the follow-up comment:
>  ...the ability to disable n-dimensional FFT planning. This can potentially accelerate nD FFTs at the cost of physically taking more GPU memory

I think you mean to accelerate nD FFTs by pre-allocating nD plans? Did I get you right @awthomp? 

You're right that the bottle neck is often at plan creation, especially when the plan size isn't a power of primes 2, 3, 5, and 7. We found using `next_fast_len()` to determine padded array sizes can be very performance-critical: https://github.com/cupy/cupy/pull/3571. Another possibility to alleviate the plan creation pain is to cache them: https://github.com/cupy/cupy/issues/3588 (discussion ongoing).

Oh, you can also create a multi-GPU FFT plan if you need 😉: https://github.com/cupy/cupy/pull/2644

**Comment by awthomp** [comment]
> I think you mean to accelerate nD FFTs by pre-allocating nD plans? Did I get you right @awthomp?

Yes, @leofang! As you probably know, many signal processing workflows start with saying "okay, I want to take M N-point FFTs, and I want to do a TON of them as data streams in." We'd like the flexibility not to pay the API overhead for cuFFT plan creation with each call to `cupy.XXX.fft`.

We're very interested in following the cached FFT plan creation and ways to reduce the overhead!

CC @dicta @boonedoggle @mnicely and @BradReesWork 

As an aside, I'll be on vacation until Aug 9th, so my responses may be a bit delayed. 

Thanks for keeping us in the loop!

**Comment by leofang** [comment]
Check out cupy/cupy#3730.
