### ISSUE TITLE
[BUG] Trouble importing cusignal

### ISSUE THREAD

**Issue by kac487** [rapidsai/cusignal#140]
Hello,
I think i am running into a bug when importing cusignal in python 3.6. It looks like it is searching for the `six` module under `scipy._lib`  Here is a capture of the stack trace I receive

```
Python 3.6.10 | packaged by conda-forge | (default, Apr 24 2020, 16:44:11) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cusignal
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/casteka1/anaconda3/envs/mlEnv/lib/python3.6/site-packages/cusignal/__init__.py", line 19, in <module>
    from cusignal.filtering.resample import (
  File "/home/casteka1/anaconda3/envs/mlEnv/lib/python3.6/site-packages/cusignal/filtering/__init__.py", line 14, in <module>
    from cusignal.filtering.resample import (
  File "/home/casteka1/anaconda3/envs/mlEnv/lib/python3.6/site-packages/cusignal/filtering/resample.py", line 26, in <module>
    from ..windows.windows import get_window
  File "/home/casteka1/anaconda3/envs/mlEnv/lib/python3.6/site-packages/cusignal/windows/__init__.py", line 14, in <module>
    from cusignal.windows.windows import (
  File "/home/casteka1/anaconda3/envs/mlEnv/lib/python3.6/site-packages/cusignal/windows/windows.py", line 18, in <module>
    from scipy._lib.six import string_types
ModuleNotFoundError: No module named 'scipy._lib.six'

```
Hare are the versions of scipy and cusignal I am running in anaconda
```
conda list | grep 'scipy\|cusignal'
cusignal                  0.14.0                   py36_0    rapidsai
scipy                     1.5.0            py36h2d22cac_0    conda-forge
```
Here is the specific conda command I used when installing cusignal
`conda install -c rapidsai -c nvidia -c conda-forge -c defaults rapids=0.14 python=3.6 cudatoolkit=10.2`

Any help would be greatly appreciated.

**Comment by awthomp** [comment]
Thanks for the detailed bug report, @kac487 -- we'll take a look!

**Comment by awthomp** [comment]
@kac487 -- We didn't force an upper limit on SciPy package compliance, so when they upgraded to 1.5, our dependency broke. We are placing a hotfix to force 1.4.1 and will look at inclusion of 1.5 in the future. Thanks so much for the bug report! This should be fixed with https://github.com/rapidsai/cusignal/pull/143

**Comment by carabedo** [comment]
Hi i tried to install cusignal on win10 using conda, i followed:

https://github.com/rapidsai/cusignal#conda-linux-os

It install succesully, but when i try to import cusignal:

`ModuleNotFoundError: No module named 'cusignal'
`

What can i do?

**Comment by awthomp** [comment]
Did you see any errors when running build.sh? Could you paste the output here?

**Comment by awthomp** [comment]
Please follow the Windows build instructions here, instead. https://github.com/rapidsai/cusignal#source-windows-os

Let us know if this doesn’t work.
