### ISSUE TITLE
[FEA] Polyphase Channelizer

### ISSUE THREAD

**Issue by boonedoggle** [rapidsai/cusignal#142]
**Is your feature request related to a problem? Please describe.**
Most applications in signal processing are predicated on channelizing a wider band signal into multiple lower bandwidth channels. 

**Describe the solution you'd like**
There are many options here and most channelizers are likely not optimized for GPU processing. Here are a few suggested implementations to get the conversation started:
* the PFB Channelzer in GNU Radio
    * https://github.com/gnuradio/gnuradio/blob/master/gr-filter/lib/pfb_channelizer_ccf_impl.cc
* Implementation from Fred Harris' paper here:
    * http://read.pudn.com/downloads157/ebook/699899/Digital%20Receivers%20and%20Transmitters%20Using%20Polyphase%20Filter%20Banks%20for%20Wireless.pdf
* Implementation from Vignesh Adhinarayanany: 
    * http://people.cs.vt.edu/~avignesh/papers/vignesh-icpads2013-sdr.pdf
* Implementation from Amean Al-safi:
    * https://www.academia.edu/25720645/GPU_based_implementation_of_a_64-channel_polyphase_channalizer

**Describe alternatives you've considered**
Currently done on FPGA. Would like to use the GPU

**Additional context**
Add any other context, code examples, or references to existing implementations about the feature request here.

**Comment by awthomp** [comment]
Thanks, @boonedoggle. I definitely want to see polyphase channelizer support in cuSignal.
