### ISSUE TITLE
[FEA] Create Logo for cuSignal

### ISSUE THREAD

**Issue by awthomp** [rapidsai/cusignal#15]
Do you love signal processing, GPUs, and graphic design? We'd love to see your ideas!

**Comment by awthomp** [comment]
![cusignal_logo_crop](https://user-images.githubusercontent.com/34922235/78993617-1461d000-7b0c-11ea-95d0-4425d455fc4d.jpg)

I don't have any clue how to create graphics, but I'd love something like this! What do ya'll think?

**Comment by marcusmueller** [comment]
I like the idea of integrating a waterfall diagram, but all in all I think this might be a bi much: Waterfall + text + Waves thingy for a logo. I'd recommend making a recognizable logo that comes with a "full version", which includes the project name, and "just the bare logo" to be used e.g. as icon on websites, etc.

As such: simply the silhuette of a PCIe card, cut out of a waterfall, with the same types of waves, emanating from where a consumer GPU card would have its video connectors?

**Comment by awthomp** [comment]
Thanks, @marcusmueller -- all very good points and ideas!

**Comment by 0xCoto** [comment]
How about this?
![logo](https://user-images.githubusercontent.com/25392776/79068672-5c7e1f80-7cd1-11ea-8cbf-3287ac4d835a.png)

**Comment by awthomp** [comment]
@0xCoto -- I love the simplicity and idea! Thanks for contributing!

**Comment by xichaoqiang** [comment]
> How about this?
> ![logo](https://user-images.githubusercontent.com/25392776/79068672-5c7e1f80-7cd1-11ea-8cbf-3287ac4d835a.png)

I think the color of cu is green better.Like the color of Nvidia cuda

**Comment by 0xCoto** [comment]
Better?
![img](https://user-images.githubusercontent.com/25392776/79212760-b2c59c80-7e50-11ea-95f5-f5b790704f53.png)

**Comment by xichaoqiang** [comment]
![image](https://user-images.githubusercontent.com/30900789/79212952-f6cd9700-7e7a-11ea-84f2-8021662f87cb.png)
change to red?

**Comment by 0xCoto** [comment]
![logo](https://user-images.githubusercontent.com/25392776/79213357-b3aafe00-7e51-11ea-840b-0e6264c19ccb.png)

**Comment by xichaoqiang** [comment]
GOOD

**Comment by awthomp** [comment]
@0xCoto -- if you wouldn't mind, could you also mock up the logo using the "RAPIDS Purples" shown [here](https://rapids.ai/index.html)? I'm thinking the light purple for the cu, dark purple for Signal, and the green for the emissions?

**Comment by 0xCoto** [comment]
Here you go. :)
![rapids](https://user-images.githubusercontent.com/25392776/79243106-de12b080-7e7d-11ea-96cc-632cbe12eda9.png)

**Comment by mpariente** [comment]
These look nice ! 
Just an suggestion, I had the logo for [Asteroid](https://github.com/mpariente/asteroid) done last week on Fiverr, it was really cheap and really fast. You might want to consider it :wink:
