### ISSUE TITLE
[BUG] cusignal.filtering.detrend throws NotImplementedError due to cp.r_

### ISSUE THREAD

**Issue by Vlad0922** [rapidsai/cusignal#151]
**Describe the bug**
Hello.
If one tries to use detrend function it throws NotImplementedError. The reason is because cp.r_ on line 566 does not work with slices. 

**Steps/Code to reproduce bug**
The bug can be reproduces with any code I have tried, even the example does not work.

```
randgen = cp.random.RandomState(9)
npoints = 1000
noise = randgen.randn(npoints)
x = 3 + 2*cp.linspace(0, 1, npoints) + noise
(cusignal.detrend(x) - noise).max() < 0.01
```

**Expected behavior**
Without exception.

**Environment details (please complete the following information):**
 - Environment location: bare-metal.
 - Method of cuSignal install: from source
 
cupy version: 7.5
cusignal version: latest

**Additional context**
The bug could be fixed simply by replacing cp.r_ with np.r_

**Comment by awthomp** [comment]
Thanks for the bug report, @Vlad0922! We'll take a look and keep this issue updated as we move forward.
