### ISSUE TITLE
[BUG] Can't run local CI build script

### ISSUE THREAD

**Issue by mnicely** [rapidsai/cusignal#154]
Has anyone successfully executed the script at https://github.com/rapidsai/cusignal/blob/branch-0.15/ci/local/build.sh
I've tried multiple docker files but it always hangs.

@efajardo-nv It looks like you were the last to commit. Can you provide any insight?

**Comment by efajardo-nv** [comment]
@mnicely gpuci recently switched to using new docker images. the local build script needs to be updated to use one of the new images. PR #153 should take care of that.
