### ISSUE TITLE
[BUG] Value Error using cupy with MappedNDArray

### ISSUE THREAD

**Issue by boonedoggle** [rapidsai/cusignal#178]
I am seeing an error when I try to copy a cupy array to a shared memory array in cuSignal. I am using a Jetson TX2.

This works
```
x0 = cusignal.get_shared_mem(2, dtype=cp.float32)
x0[:] = np.random.randn(2).astype(np.float32)
```

This does not work

```
x1 = cusignal.get_shared_mem(2, dtype=cp.float32)
x1[:] = cp.random.randn(2).astype(cp.float32)
```

The error I receive is:
```ValueError                                Traceback (most recent call last)
<ipython-input-72-9668fbf08ae6> in <module>
----> 2 x1[:] = cp.random.randn(2).astype(np.float32)

ValueError: object __array__ method not producing an array
```

Note that `cusignal.get_shared_mem` is a wrapper to `numba.cuda.mapped_array()`

**Comment by awthomp** [comment]
@boonedoggle Could you please try the following:

```python
x1 = cusignal.get_shared_mem(2, dtype=cp.float32)
x1[:] = numba.cuda.as_cuda_array(cp.random.randn(2).astype(cp.float32))
```

**Comment by awthomp** [comment]
Users experiencing this issue should leverage cupy generated `get_shared_mem` (i.e. `dtype=cp.float32` rather than `dtype=np.float32` in this case) via the following commands:

```
x1 = cusignal.get_shared_mem(2, dtype=cp.float32)
x1[:] = numba.cuda.as_cuda_array(cp.random.randn(2).astype(cp.float32))
```

The `numba.cuda` prefix isn't needed if the dtype is `np.float32`, and the code matches that given on the main README.
