### ISSUE TITLE
[FEA] Reevaluate Filter Design module for performance improvements

### ISSUE THREAD

**Issue by mnicely** [rapidsai/cusignal#229]
The Filter Design module need to be reevaluated to find areas of further performance improvements.

**Comment by awthomp** [comment]
Note: This includes similar investigations as explored in https://github.com/rapidsai/cusignal/pull/235. Developers should be examining:

- Use of numpy over cupy for small-scale calculations like overlap size, FFT size, and other generic parameters that don't require GPU compute
- Elementwise kernels, where appropriate (either raw cupy, as denoted in the above PR, or Numba)
- Caching of FFT plans
