### ISSUE TITLE
[FEA] Addition of Real and Complex Cepstrum for Speech/Acoustic Signal Processing

### ISSUE THREAD

**Issue by awthomp** [rapidsai/cusignal#23]
The Cepstrum is defined here: https://en.wikipedia.org/wiki/Cepstrum

And MATLAB/Octave have implementations of both the real/complex cepstrum documented here:
* rceps - https://www.mathworks.com/help/signal/ref/rceps.html
* cceps - https://www.mathworks.com/help/signal/ref/cceps.html

**Comment by beckernick** [comment]
I'm not a SME, but would the following be useful as test cases from Python?

https://python-acoustics.github.io/python-acoustics/cepstrum.html?highlight=cepstrum#acoustics.cepstrum.real_cepstrum
https://python-acoustics.github.io/python-acoustics/cepstrum.html?highlight=cepstrum#acoustics.cepstrum.complex_cepstrum
