### ISSUE TITLE
[BUG] Fix FFT cache w/ CuPy v8

### ISSUE THREAD

**Issue by mnicely** [rapidsai/cusignal#253]
After working on something for @awthomp, I discovered that internal FFT cache plan in CuPy v8 is more performant than the cuSignal's internal. But cuSignal's internal one is better with CuPy v7, which doesn't have a FFT cache.

**Comment by leofang** [comment]
Was waiting for your tests, Matt! Thanks a lot for confirming its performance for me 🙏 Very glad to know it helped. Do you happen to keep some performance numbers that you can share with me?

**Comment by mnicely** [comment]
> Was waiting for your tests, Matt! Thanks a lot for confirming its performance for me 🙏 Very glad to know it helped. Do you happen to keep some performance numbers that you can share with me?

Oh goodness, I didn’t realize I was keeping you waiting! I’ve add a few numbers to the PR. Let me know if you would like more!

**Comment by leofang** [comment]
Haha no worries. I figured that you'll try it out and report back at some point 😁
