### ISSUE TITLE
[FEA] Are there plans to implement higher order convolutions?

### ISSUE THREAD

**Issue by randompast** [rapidsai/cusignal#258]
Are there plans to implement higher order convolutions?  I want to calculate a volterra series: https://en.wikipedia.org/wiki/Volterra_series

I've been writing, collecting, and benchmarking convolution implementations (https://github.com/randompast/python-convolution-comparisons).  Here's a demonstration of a use case with numba.cuda: https://numba.discourse.group/t/cuda-jit-higher-order-convolution-optimizations-volterra-operator/245  The filters (k1,k2,k3) are lower triangular (to avoid permutations of x_ijk which would be redundant).

Here's the calculation for 3 filters of increasing order operating on a 1 dimensional signal.
y[n] += x[n+u1]*k1[u1] + x[n+u2]*x[n+v2]*k2[u2,v2] + x[n+u3]*x[n+v3]*x[n+w3]*k3[u3,v3,w3]

**Comment by awthomp** [comment]
Thanks for the feature request @randompast! I'm not super familiar with high order convolutions or the problems they're particularly suited to solve, but it seems like you've done some work implementing these in numba.cuda, and I'd totally merge a PR if you're keen on contributing. @mnicely could lend some cycles in terms of optimization help, as well.

**Comment by randompast** [comment]
Hey Adam, thanks!  I think my simulation is particularly slow and not yet suitable for merging.  I'm trying to speed it up.  On that note, maybe it makes sense for me to take a look at the existing cuSignal.convolve code and alter that.  I'll try doing that this week and see what I can come up with to see if a PR would work.  Thanks for the encouragement!

As for the intuition/application of convolution in my domain, I'm using it to simulate a neuron's electrical potential.  The first order convolution is effectively the impact of each moment of the past signal on the current potential.  The second order expands that to pairs of moments, third order is triples of moments, and so on.

**Comment by awthomp** [comment]
> On that note, maybe it makes sense for me to take a look at the existing cuSignal.convolve code and alter that. I'll try doing that this week and see what I can come up with to see if a PR would work. Thanks for the encouragement!

Sure! You can also take a look at `cusignal.convolve2d` (@mnicely can provide a bit more info if you have questions). One option is for you to create a Work In Progress PR, allow us to write to your branch, and we can try to work on the higher order convolutions together. Even if we ultimately decide not to merge, I do think that we may be able to get your code running quicker. 

@mnicely -- what do you think?

**Comment by mnicely** [comment]
That is a good start! When you say higher dimensions, do you have a particular dimension in mind? Or do you mean 3D, 4D, 5D, ... and so forth.

**Comment by randompast** [comment]
@mnicely Hey, thanks.  There's an important distinction to make here: Dimension and order are related but not equivalent in this context.  So, I'm looking for higher orders, not dimensions, and just up to ~3rd order would likely be sufficient for me.  Second order uses pairs of signal frames and those frames depend on the dimensionality.  A 2nd order filter on a 1D signal (ex: audio) would be a matrix dot product sliding across the 1D signal outer producted with itself.  A 1st order filter on a 3D signal (ex: video) would be a 3D block of numbers that slides over the video.  The filter's dimensionality is the order times the signal's dimensionality, so for 2nd order 3D we'd have a 6D filter.

Another GTC conference attendee sent me this implementation: https://vcl.iti.gr/new/volterra-based-convolution-filter-implementation-in-torch/  I'm digging into it now to see if it's what I hope it'd be.

**Comment by randompast** [comment]
Forked, branched (convolve_1d_2o3o), pushed, submitted pull request.

Only 'valid' implemented.  Only tested for square and cubic kernels.  Needed: tests, verification/validation, benchmarks, optimizations.

Here's a test that shows some basic timing and output.  On the second run, the new cs.convolve1d2o is ~2x faster than naive njit and ~10x faster than naive cuda.jit.  Similarly the new cs.convolve1d3o is ~100x faster than both.  Likely there's a beginner's mistake in my cuda.jit version.

[test.txt](https://github.com/rapidsai/cusignal/files/5399137/test.txt)

**Comment by randompast** [comment]
Possible further development: 
1. 3D, first and second order (signal(t,x,y) * filter(t,x,y), signal(t1,x1,y1) * filter(t2,x2,y2) * filter(t1,x1,y1,t2,x2,y2))
2. Include only 1 permutation (ij but not ji)
3. Include njitted version as cpu fallback.
4. Generalize so that there's not as much repetition.
5. Possibly include volterra as f(x,k): convolve(x,k[1], 'valid') + convolve1d2o(x,k[2]) + convolve1d3o(x,k[3])

**Comment by randompast** [comment]
(another sanity check with a mini benchmark)[https://gist.github.com/randompast/73b23a7d2560305be8bddb3a2b9f3a53]

**Comment by awthomp** [comment]
Closed with merging of @randompast 's PR here: https://github.com/rapidsai/cusignal/pull/270. Thanks for the contribution!
