### ISSUE TITLE
[QST] How to use `get_pinned_mem` for a 1D input data array

### ISSUE THREAD

**Issue by snethej** [rapidsai/cusignal#276]
**What is your question?**
Using v0.16.0, I am trying to use get_pinned_mem() from arraytools.py and if I use an int (e.g., 32768) for the shape, I get the following error:

<pre>Traceback (most recent call last):
  File &quot;./pinned.py&quot;, line 7, in &lt;module&gt;
    buff = cusignal.utils.arraytools.get_pinned_mem(32768, dtype=np.float32)
  File &quot;/home/grdcs/.conda/envs/cusignal/lib/python3.6/site-packages/cusignal-0.16.0a0+190.gc3c9d71-py3.6.egg/cusignal/utils/arraytools.py&quot;, line 129, in get_pinned_mem
    size = shape[0] * cp.dtype(dtype).itemsize
TypeError: &apos;int&apos; object is not subscriptable</pre>

The documentation seems to indicate that an int is allowed, similar to get_shared_mem(), which I use an int for it's shape.  Is that not the case?  I'm very new to cuSignal, so I'm not positive if I'm using it correctly.

I attached my simple script.
[pinned.py.gz](https://github.com/rapidsai/cusignal/files/5447591/pinned.py.gz)

**Comment by awthomp** [comment]
Hi @snethej. Welcome to cuSignal, and thanks for the question!

I took a look at your script, and you can successfully allocate this pinned memory buffer by:

```
import cusignal
import cupy as cp

buff = cusignal.get_pinned_mem((1,32768), dtype=np.float32)
```

This isn't totally clear from the documentation, and we'll be sure to fix it in a future release.
