### ISSUE TITLE
[QST] Can upfirdn use Shared Memory without a Device to Host Copy?

### ISSUE THREAD

**Issue by snethej** [rapidsai/cusignal#285]
**What is your question?**
I am using shared memory (**get_shared_mem**) as source and destination buffers for use with **upfirdn()**.  When I profile it, I am seeing a DtoH copy.

![Screenshot from 2020-11-19 10-32-39](https://user-images.githubusercontent.com/19215173/99695375-1d782f80-2a53-11eb-8cc4-9b952ec965b5.png)

I assume that it is because I have to use a **cp.asnumpy()** to assign the output of **upfirdn()**, but I have not found another way to do it without the conversion.  Is there a way to assign the output of **upfirdn()** without a DtoH copy?

Here's the short test script I am using (and I am no way a Python expert): [upfirdn_test.txt](https://github.com/rapidsai/cusignal/files/5568323/upfirdn_test.txt)

Edit:  My goal is to keep all data on the device since there will be more calculations on the device later.

**Comment by awthomp** [comment]
Thanks for the question, @snethej. This is quasi related to https://github.com/rapidsai/cusignal/issues/76 where we learned that despite having a zero-copy input memory buffer, internal memory usage and output results typically don't keep that context. @mnicely wrote the fatbin kernel for this function, so it'll be good to see if he has any suggestions. Ultimately, this is something we'd like addressed in future versions of cusignal (e.g. if you're inputting a shared-mem array, you'd ostensibly like a shared-mem array as output and not have any hard-copies in the function's internals.

**Comment by snethej** [comment]
Ah!  I did not put those two together.  That makes sense.  I suppose my question is answered.

Thanks!

**Comment by awthomp** [comment]
I'll keep this issue opened, for the time being. I'd like Matt's input too -- and, hopefully, we can start planning towards expanding functionality here.

**Comment by mnicely** [comment]
@snethej You have ran into a limitation of the API. 

There are two near term fixes
1. cuSignal determines if the inputs are pinned-mapped arrays and creates a pinned-mapped array output. :-1: 
2. The user creates a pinned-mapped output and pass to the functions. (Better function performance) :+1:

Long-term I'd like to move from Numba pinned-mapped construct to CuPy's memory block construct.
The user can declare a pinned-mapped memory construct and the module will use that memory space through the life of the kernel. With the block construct chunks are allocs and reused as needed.

**Comment by awthomp** [comment]
I'm going to close this question. As we plan out the future of cuSignal, allowing for finer memory control will be one of the key features we expand.
