### ISSUE TITLE
Use of gr-osmosdr with cuSignal[QST]

### ISSUE THREAD

**Issue by RFNOD** [rapidsai/cusignal#293]
**What is your question?**

Is it possible to use gr-osmosdr with cuSignal? or is it limited to just SoapySDR because it uses python? I am curious and this is bit out of the box. Thanks!!

**Comment by awthomp** [comment]
Hi @RFNOD -- Thanks for asking a question!

I've muddled around with cuSignal and gnuradio integration, in general, and have seen some success by building a signal processing workflow in gnuradio-companion, looking at the resulting Python code, and plopping cuSignal into that. From an install side of the house, you can get cuSignal to work nicely with gnuradio (and gr-osmosdr!) in general by creating a standalone Anaconda environment.

Luckily, it's easy to install gnuradio via conda with:
`conda install -c conda-forge gnuradio`

You can also find SDR specific plugins, including gr-osmosdr, also via conda:
`conda install -c conda-forge gnuradio-osmosdr`. 

More info [here](https://anaconda.org/search?q=gnuradio).

You can then install the cuSignal package via conda install in the same environment.

I'm always looking for more ways for cuSignal to intersect with the gnuradio community and project and welcome your help and suggestions!

**Comment by RFNOD** [comment]
Thank you @awthomp !!! I will do that!!
