### ISSUE TITLE
[BUG]  test_wiener unit test fails 

### ISSUE THREAD

**Issue by devnulling** [rapidsai/cusignal#3]
**Describe the bug**
Wiener test fails

**Steps/Code to reproduce bug**
run `pytest -v`

**Expected behavior**
no failures with unit tests

**Environment details (please complete the following information):**
- ubuntu 18.04
- conda install
- py 3.7

**Additional context**
$ pytest -v
=========================================================== test session starts ============================================================
platform linux -- Python 3.7.3, pytest-5.2.4, py-1.8.0, pluggy-0.13.0 -- /home/user/anaconda3/envs/cusignal/bin/python
cachedir: .pytest_cache
rootdir: /home/user/cusignal
collected 123 items                                                                                                                        

cusignal/test/test_signaltools.py::test_resample[window0-4096-16384] PASSED                                                          [  0%]
cusignal/test/test_signaltools.py::test_resample[window0-65536-16384] PASSED                                                         [  1%]
cusignal/test/test_signaltools.py::test_resample_poly[window0-1-2-16384] PASSED                                                      [  2%]
cusignal/test/test_signaltools.py::test_resample_poly[window0-1-3-16384] PASSED                                                      [  3%]
cusignal/test/test_signaltools.py::test_resample_poly[window0-1-7-16384] PASSED                                                      [  4%]
cusignal/test/test_signaltools.py::test_resample_poly[window0-2-2-16384] PASSED                                                      [  4%]
cusignal/test/test_signaltools.py::test_resample_poly[window0-2-3-16384] PASSED                                                      [  5%]
cusignal/test/test_signaltools.py::test_resample_poly[window0-2-7-16384] PASSED                                                      [  6%]
cusignal/test/test_signaltools.py::test_resample_poly[window0-9-2-16384] PASSED                                                      [  7%]
cusignal/test/test_signaltools.py::test_resample_poly[window0-9-3-16384] PASSED                                                      [  8%]
cusignal/test/test_signaltools.py::test_resample_poly[window0-9-7-16384] PASSED                                                      [  8%]
cusignal/test/test_signaltools.py::test_firwin[0.2-0.1-32768] PASSED                                                                 [  9%]
cusignal/test/test_signaltools.py::test_firwin[0.2-0.15-32768] PASSED                                                                [ 10%]
cusignal/test/test_signaltools.py::test_firwin[0.4-0.1-32768] PASSED                                                                 [ 11%]
cusignal/test/test_signaltools.py::test_firwin[0.4-0.15-32768] PASSED                                                                [ 12%]
cusignal/test/test_signaltools.py::test_correlate[128-32768] PASSED                                                                  [ 13%]
cusignal/test/test_signaltools.py::test_correlate[256-32768] PASSED                                                                  [ 13%]
cusignal/test/test_signaltools.py::test_correlate[32768-32768] PASSED                                                                [ 14%]
cusignal/test/test_signaltools.py::test_convolve[128-32768] PASSED                                                                   [ 15%]
cusignal/test/test_signaltools.py::test_convolve[256-32768] PASSED                                                                   [ 16%]
cusignal/test/test_signaltools.py::test_convolve[32768-32768] PASSED                                                                 [ 17%]
cusignal/test/test_signaltools.py::test_fftconvolve[32768] PASSED                                                                    [ 17%]
cusignal/test/test_signaltools.py::test_wiener[32768] FAILED                                                                         [ 18%]
cusignal/test/test_signaltools.py::test_wiener[16777216] PASSED                                                                      [ 19%]
cusignal/test/test_signaltools.py::test_hilbert[32768] PASSED                                                                        [ 20%]
cusignal/test/test_signaltools.py::test_hilbert2[256] PASSED                                                                         [ 21%]
cusignal/test/test_signaltools.py::test_convolve2d[same-symm-5-256] PASSED                                                           [ 21%]
cusignal/test/test_signaltools.py::test_convolve2d[same-symm-100-256] PASSED                                                         [ 22%]
cusignal/test/test_signaltools.py::test_correlate2d[same-symm-5-256] PASSED                                                          [ 23%]
cusignal/test/test_signaltools.py::test_correlate2d[same-symm-100-256] PASSED                                                        [ 24%]
cusignal/test/test_spectral.py::test_csd[1024-1.0-16384] PASSED                                                                      [ 25%]
cusignal/test/test_spectral.py::test_csd[1024-1000000.0-16384] PASSED                                                                [ 26%]
cusignal/test/test_spectral.py::test_csd[2048-1.0-16384] PASSED                                                                      [ 26%]
cusignal/test/test_spectral.py::test_csd[2048-1000000.0-16384] PASSED                                                                [ 27%]
cusignal/test/test_spectral.py::test_csd_complex[1024-1.0-16384] PASSED                                                              [ 28%]
cusignal/test/test_spectral.py::test_csd_complex[1024-1000000.0-16384] PASSED                                                        [ 29%]
cusignal/test/test_spectral.py::test_csd_complex[2048-1.0-16384] PASSED                                                              [ 30%]
cusignal/test/test_spectral.py::test_csd_complex[2048-1000000.0-16384] PASSED                                                        [ 30%]
cusignal/test/test_spectral.py::test_periodogram[spectrum-flattop-1.0-16384] PASSED                                                  [ 31%]
cusignal/test/test_spectral.py::test_periodogram[spectrum-flattop-1000000.0-16384] PASSED                                            [ 32%]
cusignal/test/test_spectral.py::test_periodogram[spectrum-nuttall-1.0-16384] PASSED                                                  [ 33%]
cusignal/test/test_spectral.py::test_periodogram[spectrum-nuttall-1000000.0-16384] PASSED                                            [ 34%]
cusignal/test/test_spectral.py::test_periodogram[density-flattop-1.0-16384] PASSED                                                   [ 34%]
cusignal/test/test_spectral.py::test_periodogram[density-flattop-1000000.0-16384] PASSED                                             [ 35%]
cusignal/test/test_spectral.py::test_periodogram[density-nuttall-1.0-16384] PASSED                                                   [ 36%]
cusignal/test/test_spectral.py::test_periodogram[density-nuttall-1000000.0-16384] PASSED                                             [ 37%]
cusignal/test/test_spectral.py::test_periodogram_complex[spectrum-flattop-1.0-16384] PASSED                                          [ 38%]
cusignal/test/test_spectral.py::test_periodogram_complex[spectrum-flattop-1000000.0-16384] PASSED                                    [ 39%]
cusignal/test/test_spectral.py::test_periodogram_complex[spectrum-nuttall-1.0-16384] PASSED                                          [ 39%]
cusignal/test/test_spectral.py::test_periodogram_complex[spectrum-nuttall-1000000.0-16384] PASSED                                    [ 40%]
cusignal/test/test_spectral.py::test_periodogram_complex[density-flattop-1.0-16384] PASSED                                           [ 41%]
cusignal/test/test_spectral.py::test_periodogram_complex[density-flattop-1000000.0-16384] PASSED                                     [ 42%]
cusignal/test/test_spectral.py::test_periodogram_complex[density-nuttall-1.0-16384] PASSED                                           [ 43%]
cusignal/test/test_spectral.py::test_periodogram_complex[density-nuttall-1000000.0-16384] PASSED                                     [ 43%]
cusignal/test/test_spectral.py::test_welch[1024-1.0-16384] PASSED                                                                    [ 44%]
cusignal/test/test_spectral.py::test_welch[1024-1000000.0-16384] PASSED                                                              [ 45%]
cusignal/test/test_spectral.py::test_welch[2048-1.0-16384] PASSED                                                                    [ 46%]
cusignal/test/test_spectral.py::test_welch[2048-1000000.0-16384] PASSED                                                              [ 47%]
cusignal/test/test_spectral.py::test_welch_complex[1024-1.0-16384] PASSED                                                            [ 47%]
cusignal/test/test_spectral.py::test_welch_complex[1024-1000000.0-16384] PASSED                                                      [ 48%]
cusignal/test/test_spectral.py::test_welch_complex[2048-1.0-16384] PASSED                                                            [ 49%]
cusignal/test/test_spectral.py::test_welch_complex[2048-1000000.0-16384] PASSED                                                      [ 50%]
cusignal/test/test_spectral.py::test_spectrogram[1.0-16384] PASSED                                                                   [ 51%]
cusignal/test/test_spectral.py::test_spectrogram[1000000.0-16384] PASSED                                                             [ 52%]
cusignal/test/test_spectral.py::test_spectrogram_complex[1.0-16384] PASSED                                                           [ 52%]
cusignal/test/test_spectral.py::test_spectrogram_complex[1000000.0-16384] PASSED                                                     [ 53%]
cusignal/test/test_spectral.py::test_coherence[1024-1.0-16384] PASSED                                                                [ 54%]
cusignal/test/test_spectral.py::test_coherence[1024-1000000.0-16384] PASSED                                                          [ 55%]
cusignal/test/test_spectral.py::test_coherence[2048-1.0-16384] PASSED                                                                [ 56%]
cusignal/test/test_spectral.py::test_coherence[2048-1000000.0-16384] PASSED                                                          [ 56%]
cusignal/test/test_spectral.py::test_coherence_complex[1024-1.0-16384] PASSED                                                        [ 57%]
cusignal/test/test_spectral.py::test_coherence_complex[1024-1000000.0-16384] PASSED                                                  [ 58%]
cusignal/test/test_spectral.py::test_coherence_complex[2048-1.0-16384] PASSED                                                        [ 59%]
cusignal/test/test_spectral.py::test_coherence_complex[2048-1000000.0-16384] PASSED                                                  [ 60%]
cusignal/test/test_spectral.py::test_stft[1024-1.0-16384] PASSED                                                                     [ 60%]
cusignal/test/test_spectral.py::test_stft[1024-1000000.0-16384] PASSED                                                               [ 61%]
cusignal/test/test_spectral.py::test_stft[2048-1.0-16384] PASSED                                                                     [ 62%]
cusignal/test/test_spectral.py::test_stft[2048-1000000.0-16384] PASSED                                                               [ 63%]
cusignal/test/test_spectral.py::test_stft_complex[1024-1.0-16384] PASSED                                                             [ 64%]
cusignal/test/test_spectral.py::test_stft_complex[1024-1000000.0-16384] PASSED                                                       [ 65%]
cusignal/test/test_spectral.py::test_stft_complex[2048-1.0-16384] PASSED                                                             [ 65%]
cusignal/test/test_spectral.py::test_stft_complex[2048-1000000.0-16384] PASSED                                                       [ 66%]
cusignal/test/test_waveforms.py::test_square[0.25-16384] PASSED                                                                      [ 67%]
cusignal/test/test_waveforms.py::test_square[0.5-16384] PASSED                                                                       [ 68%]
cusignal/test/test_waveforms.py::test_gausspulse[0.75-16384] PASSED                                                                  [ 69%]
cusignal/test/test_waveforms.py::test_gausspulse[5-16384] PASSED                                                                     [ 69%]
cusignal/test/test_waveforms.py::test_chirp[linear-10-1-6-16384] PASSED                                                              [ 70%]
cusignal/test/test_waveforms.py::test_chirp[quadratic-10-1-6-16384] PASSED                                                           [ 71%]
cusignal/test/test_waveforms.py::test_unit_impulse[mid-16384] PASSED                                                                 [ 72%]
cusignal/test/test_wavelets.py::test_morlet[16384] PASSED                                                                            [ 73%]
cusignal/test/test_wavelets.py::test_ricker[10-16384] PASSED                                                                         [ 73%]
cusignal/test/test_wavelets.py::test_ricker[1000-16384] PASSED                                                                       [ 74%]
cusignal/test/test_wavelets.py::test_cwt[31-16384] PASSED                                                                            [ 75%]
cusignal/test/test_wavelets.py::test_cwt[127-16384] PASSED                                                                           [ 76%]
cusignal/test/test_wavelets.py::test_cwt_complex[31-16384] PASSED                                                                    [ 77%]
cusignal/test/test_wavelets.py::test_cwt_complex[127-16384] PASSED                                                                   [ 78%]
cusignal/test/test_windows.py::test_general_cosine[32768] PASSED                                                                     [ 78%]
cusignal/test/test_windows.py::test_boxcar[32768] PASSED                                                                             [ 79%]
cusignal/test/test_windows.py::test_triang[32768] PASSED                                                                             [ 80%]
cusignal/test/test_windows.py::test_bohman[32768] PASSED                                                                             [ 81%]
cusignal/test/test_windows.py::test_blackman[32768] PASSED                                                                           [ 82%]
cusignal/test/test_windows.py::test_nuttall[32768] PASSED                                                                            [ 82%]
cusignal/test/test_windows.py::test_blackmanharris[32768] PASSED                                                                     [ 83%]
cusignal/test/test_windows.py::test_flattop[32768] PASSED                                                                            [ 84%]
cusignal/test/test_windows.py::test_barlett[32768] PASSED                                                                            [ 85%]
cusignal/test/test_windows.py::test_hann[32768] PASSED                                                                               [ 86%]
cusignal/test/test_windows.py::test_tukey[0.25-32768] PASSED                                                                         [ 86%]
cusignal/test/test_windows.py::test_tukey[0.5-32768] PASSED                                                                          [ 87%]
cusignal/test/test_windows.py::test_barthann[32768] PASSED                                                                           [ 88%]
cusignal/test/test_windows.py::test_general_hamming[0.25-32768] PASSED                                                               [ 89%]
cusignal/test/test_windows.py::test_general_hamming[0.5-32768] PASSED                                                                [ 90%]
cusignal/test/test_windows.py::test_hamming[32768] PASSED                                                                            [ 91%]
cusignal/test/test_windows.py::test_kaiser[0.25-32768] PASSED                                                                        [ 91%]
cusignal/test/test_windows.py::test_kaiser[0.5-32768] PASSED                                                                         [ 92%]
cusignal/test/test_windows.py::test_gaussian[3-0.75-32768] PASSED                                                                    [ 93%]
cusignal/test/test_windows.py::test_gaussian[3-1.5-32768] PASSED                                                                     [ 94%]
cusignal/test/test_windows.py::test_gaussian[7-0.75-32768] PASSED                                                                    [ 95%]
cusignal/test/test_windows.py::test_gaussian[7-1.5-32768] PASSED                                                                     [ 95%]
cusignal/test/test_windows.py::test_general_gaussian[3-32768] PASSED                                                                 [ 96%]
cusignal/test/test_windows.py::test_general_gaussian[7-32768] PASSED                                                                 [ 97%]
cusignal/test/test_windows.py::test_cosine[32768] PASSED                                                                             [ 98%]
cusignal/test/test_windows.py::test_exponential[1.5-32768] PASSED                                                                    [ 99%]
cusignal/test/test_windows.py::test_exponential[3.0-32768] PASSED                                                                    [100%]

================================================================= FAILURES =================================================================
____________________________________________________________ test_wiener[32768] ____________________________________________________________

num_samps = 32768

    @pytest.mark.parametrize('num_samps', [2**15, 2**24])
    def test_wiener(num_samps):
        cpu_sig = np.random.rand(num_samps)
        gpu_sig = cp.asarray(cpu_sig)
    
        cpu_wfilt = signal.wiener(cpu_sig)
>       gpu_wfilt = cp.asnumpy(cusignal.wiener(gpu_sig))

cusignal/test/test_signaltools.py:82: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
cusignal/signaltools.py:802: in wiener
    lMean = correlate(im, ones(mysize), 'same') / prod(mysize, axis=0)
cusignal/signaltools.py:174: in correlate
    return convolve(in1, _reverse_and_conj(in2), mode, method)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

in1 = array([0.28732198, 0.11066993, 0.30881489, ..., 0.75464472, 0.09631769,
       0.90614553]), in2 = array([1., 1., 1.]), mode = 'same'
method = 'direct'

    def convolve(in1, in2, mode='full', method='auto'):
        """
        Convolve two N-dimensional arrays.
    
        Convolve `in1` and `in2`, with the output size determined by the
        `mode` argument.
    
        Parameters
        ----------
        in1 : array_like
            First input.
        in2 : array_like
            Second input. Should have the same number of dimensions as `in1`.
        mode : str {'full', 'valid', 'same'}, optional
            A string indicating the size of the output:
    
            ``full``
               The output is the full discrete linear convolution
               of the inputs. (Default)
            ``valid``
               The output consists only of those elements that do not
               rely on the zero-padding. In 'valid' mode, either `in1` or `in2`
               must be at least as large as the other in every dimension.
            ``same``
               The output is the same size as `in1`, centered
               with respect to the 'full' output.
        method : str {'auto', 'direct', 'fft'}, optional
            A string indicating which method to use to calculate the convolution.
    
            ``direct``
               The convolution is determined directly from sums, the definition of
               convolution.
            ``fft``
               The Fourier Transform is used to perform the convolution by calling
               `fftconvolve`.
            ``auto``
               Automatically chooses direct or Fourier method based on an estimate
               of which is faster (default).  See Notes for more detail.
    
               .. versionadded:: 0.19.0
    
        Returns
        -------
        convolve : array
            An N-dimensional array containing a subset of the discrete linear
            convolution of `in1` with `in2`.
    
        See Also
        --------
        numpy.polymul : performs polynomial multiplication (same operation, but
                        also accepts poly1d objects)
        choose_conv_method : chooses the fastest appropriate convolution method
        fftconvolve
    
        Notes
        -----
        By default, `convolve` and `correlate` use ``method='auto'``, which calls
        `choose_conv_method` to choose the fastest method using pre-computed
        values (`choose_conv_method` can also measure real-world timing with a
        keyword argument). Because `fftconvolve` relies on floating point numbers,
        there are certain constraints that may force `method=direct` (more detail
        in `choose_conv_method` docstring).
    
        Examples
        --------
        Smooth a square pulse using a Hann window:
    
        >>> from scipy import signal
        >>> sig = np.repeat([0., 1., 0.], 100)
        >>> win = signal.hann(50)
        >>> filtered = signal.convolve(sig, win, mode='same') / sum(win)
    
        >>> import matplotlib.pyplot as plt
        >>> fig, (ax_orig, ax_win, ax_filt) = plt.subplots(3, 1, sharex=True)
        >>> ax_orig.plot(sig)
        >>> ax_orig.set_title('Original pulse')
        >>> ax_orig.margins(0, 0.1)
        >>> ax_win.plot(win)
        >>> ax_win.set_title('Filter impulse response')
        >>> ax_win.margins(0, 0.1)
        >>> ax_filt.plot(filtered)
        >>> ax_filt.set_title('Filtered signal')
        >>> ax_filt.margins(0, 0.1)
        >>> fig.tight_layout()
        >>> fig.show()
    
        """
        volume = asarray(in1)
        kernel = asarray(in2)
    
        if volume.ndim == kernel.ndim == 0:
            return volume * kernel
        elif volume.ndim != kernel.ndim:
            raise ValueError("volume and kernel should have the same "
                             "dimensionality")
    
        if _inputs_swap_needed(mode, volume.shape, kernel.shape):
            # Convolution is commutative; order doesn't have any effect on output
            volume, kernel = kernel, volume
    
        if method == 'auto':
            method = choose_conv_method(volume, kernel, mode=mode)
    
        if method == 'fft':
            out = fftconvolve(volume, kernel, mode=mode)
            result_type = cp.result_type(volume, kernel)
            if result_type.kind in {'u', 'i'}:
                out = cp.around(out)
            return out.astype(result_type)
        elif method == 'direct':
            # fastpath to faster numpy.convolve for 1d inputs when possible
            if _np_conv_ok(volume, kernel, mode):
>               return cp.convolve(volume, kernel, mode)
E               AttributeError: module 'cupy' has no attribute 'convolve'

cusignal/signaltools.py:760: AttributeError
============================================================= warnings summary =============================================================
/home/user/anaconda3/envs/cusignal/lib/python3.7/site-packages/numba/types/containers.py:3
  /home/user/anaconda3/envs/cusignal/lib/python3.7/site-packages/numba/types/containers.py:3: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
    from collections import Iterable

cusignal/test/test_spectral.py::test_csd_complex[1024-1.0-16384]
cusignal/test/test_spectral.py::test_csd_complex[1024-1000000.0-16384]
cusignal/test/test_spectral.py::test_csd_complex[2048-1.0-16384]
cusignal/test/test_spectral.py::test_csd_complex[2048-1000000.0-16384]
cusignal/test/test_spectral.py::test_periodogram_complex[spectrum-flattop-1.0-16384]
cusignal/test/test_spectral.py::test_periodogram_complex[spectrum-flattop-1000000.0-16384]
cusignal/test/test_spectral.py::test_periodogram_complex[spectrum-nuttall-1.0-16384]
cusignal/test/test_spectral.py::test_periodogram_complex[spectrum-nuttall-1000000.0-16384]
cusignal/test/test_spectral.py::test_periodogram_complex[density-flattop-1.0-16384]
cusignal/test/test_spectral.py::test_periodogram_complex[density-flattop-1000000.0-16384]
cusignal/test/test_spectral.py::test_periodogram_complex[density-nuttall-1.0-16384]
cusignal/test/test_spectral.py::test_periodogram_complex[density-nuttall-1000000.0-16384]
cusignal/test/test_spectral.py::test_welch_complex[1024-1.0-16384]
cusignal/test/test_spectral.py::test_welch_complex[1024-1000000.0-16384]
cusignal/test/test_spectral.py::test_welch_complex[2048-1.0-16384]
cusignal/test/test_spectral.py::test_welch_complex[2048-1000000.0-16384]
cusignal/test/test_spectral.py::test_spectrogram_complex[1.0-16384]
cusignal/test/test_spectral.py::test_spectrogram_complex[1000000.0-16384]
cusignal/test/test_spectral.py::test_coherence_complex[1024-1.0-16384]
cusignal/test/test_spectral.py::test_coherence_complex[1024-1000000.0-16384]
cusignal/test/test_spectral.py::test_coherence_complex[2048-1.0-16384]
cusignal/test/test_spectral.py::test_coherence_complex[2048-1000000.0-16384]
cusignal/test/test_spectral.py::test_stft_complex[1024-1.0-16384]
cusignal/test/test_spectral.py::test_stft_complex[1024-1000000.0-16384]
cusignal/test/test_spectral.py::test_stft_complex[2048-1.0-16384]
cusignal/test/test_spectral.py::test_stft_complex[2048-1000000.0-16384]
  /home/user/anaconda3/envs/cusignal/lib/python3.7/site-packages/scipy/signal/spectral.py:1818: UserWarning: Input data is complex, switching to return_onesided=False
    warnings.warn('Input data is complex, switching to '

cusignal/test/test_spectral.py::test_csd_complex[1024-1.0-16384]
cusignal/test/test_spectral.py::test_csd_complex[1024-1000000.0-16384]
cusignal/test/test_spectral.py::test_csd_complex[2048-1.0-16384]
cusignal/test/test_spectral.py::test_csd_complex[2048-1000000.0-16384]
cusignal/test/test_spectral.py::test_periodogram_complex[spectrum-flattop-1.0-16384]
cusignal/test/test_spectral.py::test_periodogram_complex[spectrum-flattop-1000000.0-16384]
cusignal/test/test_spectral.py::test_periodogram_complex[spectrum-nuttall-1.0-16384]
cusignal/test/test_spectral.py::test_periodogram_complex[spectrum-nuttall-1000000.0-16384]
cusignal/test/test_spectral.py::test_periodogram_complex[density-flattop-1.0-16384]
cusignal/test/test_spectral.py::test_periodogram_complex[density-flattop-1000000.0-16384]
cusignal/test/test_spectral.py::test_periodogram_complex[density-nuttall-1.0-16384]
cusignal/test/test_spectral.py::test_periodogram_complex[density-nuttall-1000000.0-16384]
cusignal/test/test_spectral.py::test_welch_complex[1024-1.0-16384]
cusignal/test/test_spectral.py::test_welch_complex[1024-1000000.0-16384]
cusignal/test/test_spectral.py::test_welch_complex[2048-1.0-16384]
cusignal/test/test_spectral.py::test_welch_complex[2048-1000000.0-16384]
cusignal/test/test_spectral.py::test_spectrogram_complex[1.0-16384]
cusignal/test/test_spectral.py::test_spectrogram_complex[1000000.0-16384]
cusignal/test/test_spectral.py::test_coherence_complex[1024-1.0-16384]
cusignal/test/test_spectral.py::test_coherence_complex[1024-1000000.0-16384]
cusignal/test/test_spectral.py::test_coherence_complex[2048-1.0-16384]
cusignal/test/test_spectral.py::test_coherence_complex[2048-1000000.0-16384]
cusignal/test/test_spectral.py::test_stft_complex[1024-1.0-16384]
cusignal/test/test_spectral.py::test_stft_complex[1024-1000000.0-16384]
cusignal/test/test_spectral.py::test_stft_complex[2048-1.0-16384]
cusignal/test/test_spectral.py::test_stft_complex[2048-1000000.0-16384]
  /home/user/cusignal/cusignal/spectral.py:1272: UserWarning: Input data is complex, switching to return_onesided=False
    warnings.warn('Input data is complex, switching to '

cusignal/test/test_wavelets.py::test_cwt_complex[31-16384]
cusignal/test/test_wavelets.py::test_cwt_complex[127-16384]
  /home/user/anaconda3/envs/cusignal/lib/python3.7/site-packages/scipy/signal/wavelets.py:364: ComplexWarning: Casting complex values to real discards the imaginary part
    mode='same')

-- Docs: https://docs.pytest.org/en/latest/warnings.html
========================================== 1 failed, 122 passed, 55 warnings in 108.07s (0:01:48) ==========================================
(cusignal) user@computer:~/cusignal$

**Comment by awthomp** [comment]
Thanks for filing an issue, @devnulling!

Like with SciPy Signal, cuSignal's convolve method chooses either an FFT or Direct version of convolution. For shorter duration/length signals, it's actually slower to do the FFT based method with standard NumPy. 

This would be a good PR with a couple options:
1. Remove the direct/fft method check and just default to the FFT approach
2. Change the direct method convolution from cupy.convolve (which isn't implemented) to numpy.convolve and run this on CPU; we're at a short signal anyway!
3. Raise a not implemented flag

I haven't benchmarked which of the above would be best, but I think this would be a good first issue for someone :).
