### ISSUE TITLE
[QST] Using C code directly

### ISSUE THREAD

**Issue by eldaromer** [rapidsai/cusignal#318]
**What is your question?**
Hi, I'd like to be able to use the C code for the 1D correlation directly instead of through python. I'm a little confused about which functions I should be using and what the inputs are.

Any help in figuring this out would be appreciated, and example code would be even more appreciated.

Thank you

**Comment by awthomp** [comment]
Hi @eldaromer. Thanks for submitting a question. cuSignal is currently a Python only library, but we've had many requests to build out a proper C/C++ layer for the API. Ideally, adding in this layer would be seamless to the Python user of cuSignal, but if you want to build a workflow in C, you could do so. We're currently scoping the engineering effort to do this and would most likely roll out support one function at a time.

That said, we do have raw CUDA files (located [here](https://github.com/rapidsai/cusignal/tree/branch-0.18/cpp/src) that you can copy/compile yourself).
