### ISSUE TITLE
"build.sh" does not automatically find GPU on a Jetson and compiles for all architectures [BUG]

### ISSUE THREAD

**Issue by znmeb** [rapidsai/cusignal#326]
**Steps/Code to reproduce bug**
Follow the instructions on this repo's README. When you get to the "build.sh" step, it will do this:

```
➤ ./build.sh                                                                                                                                                          (base)
Building for the architecture of the GPU in the system...
Unable to determine GPU(s) installed...
Building for *ALL* supported GPU architectures...
         including: CUDA 10.X - {50,52,53,60,61,62,70,72,75}
```

**Expected behavior**
I expected it to see I was on an AGX-Xavier and only build for that GPU.

**Environment details:**
 - Environment location: AGX Xavier, both on the device itself and in the NGC "ML" container
 - Method of cuSignal install: conda 

**Additional context**
I looked at the script and it's doing this:

```
NUMGPU=`lspci | grep VGA | grep NVIDIA | wc -l`
```

On the AGX Xavier, `lspci` only returns this:

```
➤ lspci                                                                                                                                                               (base)
0001:00:00.0 PCI bridge: NVIDIA Corporation Device 1ad2 (rev a1)
0001:01:00.0 SATA controller: Marvell Technology Group Ltd. Device 9171 (rev 13)
```

**Comment by awthomp** [comment]
Thanks for reporting this, @znmeb. I'll take a look over this week. The Jetson Xavier is CC 72, so it should be working.

**Comment by znmeb** [comment]
Yeah, it works. Since I went ahead and set the environment variable to specify the GPU for the `cupy` build, I figured you could accept the same variable building `cusignal` - leave it up to the user on Jetsons, since it works fine on `x86_64` as is.

**Comment by awthomp** [comment]
> Yeah, it works. Since I went ahead and set the environment variable to specify the GPU for the `cupy` build, I figured you could accept the same variable building `cusignal` - leave it up to the user on Jetsons, since it works fine on `x86_64` as is.

I'm confused. If you follow the build instructions listed on the main README for cuSignal, from source, on a Jetson, `./build.sh` does or doesn't error out? Are you just saying that the build script doesn't recognize the CC 72 and therefore builds for all compute architectures? In other words, cuSignal builds successfully, but the build process is too long?

Thanks!

**Comment by znmeb** [comment]
Sorry ... I miswrote the bug report. `cusignal` compiles for all GPUs and executes correctly on the Jetson ... it just doesn't detect the GPU so it builds all of the versions.

**Comment by awthomp** [comment]
Thanks for the clarification! We'll take a look :).

**Comment by evanmayer** [comment]
I ran into this issue too. @awthomp's suggestion of `export CUDA_VISIBLE_DEVICES=0` yields

```bash
Building for the architecture of the GPU in the system...
        Device 0 - CC 53
```

which seems like the intended behavior when following the Jetson build instructions.

**Comment by awthomp** [comment]
Thanks for confirming, @evanmayer. I'm going to close this issue as it seems there's an acceptable work-around.
