### ISSUE TITLE
Error in the SOS filter implementation comments

### ISSUE THREAD

**Issue by kykc** [rapidsai/cusignal#345]
## Error in the SOS filter implementation comments

**Location of incorrect documentation**
https://github.com/rapidsai/cusignal/blob/branch-0.19/cpp/src/filtering/_sosfilt.cu#L47

**Describe the problems or issues found in the documentation**
```
    // Load SOS
    // b is in s_sos[tx * sos_width + [0-2]]
    // a is in s_sos[tx * sos_width + [3-6]]
```
should be
```
    // Load SOS
    // b is in s_sos[tx * sos_width + [0-2]]
    // a is in s_sos[tx * sos_width + [3-5]]
```

**Steps taken to verify documentation is incorrect**
SOS filter has 3 numerator coefficients and 3 denominator coefficients

**Suggested fix for documentation**
```
    // Load SOS
    // b is in s_sos[tx * sos_width + [0-2]]
    // a is in s_sos[tx * sos_width + [3-5]]
```

**Comment by awthomp** [comment]
Hey @kykc -- Thanks for the report. I agree that this is an error in the docs. Would you feel comfortable submitting a PR? I'd be happy to walk you through the process if needed.

**Comment by awthomp** [comment]
Closed with https://github.com/rapidsai/cusignal/pull/347
