### ISSUE TITLE
[QST] KalmanFilter example NameError: name 'dt' is not defined

### ISSUE THREAD

**Issue by apiszcz** [rapidsai/cusignal#350]
In the second notebook cell at https://docs.rapids.ai/api/cusignal/nightly/api.html#kalman-filter I am getting a NameError.

![image](https://user-images.githubusercontent.com/1430861/115141833-6507e500-a00c-11eb-92c7-96f02be34374.png)

**Comment by apiszcz** [comment]
I'm replacing dt with cp.float64.

**Comment by awthomp** [comment]
Hey @apiszcz, looks like you resolved your question. Do you think the notebook/docs need to be improved? Otherwise, can I close the question?

**Comment by apiszcz** [comment]
Yes, they should be updated to define variables that are required later.
