### ISSUE TITLE
[QST] KalmanFilter example: NameError: name 'get_sensor_reading' is not defined

### ISSUE THREAD

**Issue by apiszcz** [rapidsai/cusignal#352]
​---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-29-fe4a712ab3cd> in <module>
      1 kf.predict()
----> 2 z = get_sensor_reading() (dim_z, 1)
      3 kf.z = cp.repeat(z[cp.newaxis, :, :], points, axis=0)
      4 kf.update()

NameError: name 'get_sensor_reading' is not defined

**Comment by awthomp** [comment]
Hey @apiszcz -- it's been awhile since I've run through this Jupyter notebook, but we have it behind CI/CD. Can you confirm that you ran the cells in order?

**Comment by apiszcz** [comment]
Yes, they were run in order.
