### ISSUE TITLE
[QST]CUDA_ERROR_NO_BINARY_FOR_GPU

### ISSUE THREAD

**Issue by leyojoseph** [rapidsai/cusignal#355]
Hello,
Below lines show  gpu structure in my PC

import numba.cuda as cu

cu.detect()
Found 2 CUDA devices
id 0           b'Tesla K40c'                              [SUPPORTED]
                      compute capability: 3.5
                           pci device id: 0
                              pci bus id: 3
id 1          b'Quadro K620'                              [SUPPORTED]
                      compute capability: 5.0
                           pci device id: 0
                              pci bus id: 2
Summary:
	2/2 devices are supported

I am trying to run  the below sample code.
import cusignal
import cupy as cp

sig = cp.repeat(cp.asarray([0., 1., 0.]), 100)
win = cusignal.hann(50)
filtered = cusignal.convolve(sig, win, mode='same') / cp.sum(win)

Getting the below error message.
CUDADriverError: CUDA_ERROR_NO_BINARY_FOR_GPU: no kernel image is available for execution on the device

1.I read elsewhere that Tesl K40C CC is 3.5 and not supported and need to compile code from source. Could you  please explain how to do this?
2. Is it possible to shift the used GPU to K620 which has CC 5?. If yes, how to do ?
Thanks
Leyo Joseph

**Comment by awthomp** [comment]
Hey @leyojoseph

We haven't ever tested for Kepler (only down to Maxwell) -- so I'm happy to help here. One quick question -- where do you receive your CUDA error message? After the cupy call (`cp.repeat`) or after cusignal (`cusignal.convolve`)?

We have a custom CUDA kernel used in `convolve`, so I'm assuming what's happening is that cupy works, most of cusignal works, but you're hitting an error with our custom, fast kernels.

Could you do me a favor and try to do a source build of cusignal?

Instructions here: https://github.com/rapidsai/cusignal#source-linux-os

Prior to running `./build.sh`, edit this file and add a 35 to all relevant lines here: https://github.com/rapidsai/cusignal/blob/branch-0.20/build.sh#L126-L150

@mnicely -- anything in the custom CUDA kernels that prevents Kepler from working?

**Comment by mnicely** [comment]
@leyojoseph cuSignal does officially support Kepler architecture.

Per @awthomp comment you can try adding `--generate-code arch=compute_35,code=sm35` to `./build.sh`. See snippet below.

Please note that the Kepler products have been deprecated and will not be compatible with future releases of CUDA Toolkit.

```bash
RETURN_ALL(){
    echo "Building for *ALL* supported GPU architectures..."
    GPU_ARCH="--generate-code arch=compute_50,code=sm_50 \
        --generate-code arch=compute_50,code=sm_52 \
        --generate-code arch=compute_53,code=sm_53 \
        --generate-code arch=compute_60,code=sm_60 \
        --generate-code arch=compute_61,code=sm_61 \
        --generate-code arch=compute_62,code=sm_62 \
        --generate-code arch=compute_70,code=sm_70 \
        --generate-code arch=compute_72,code=sm_72"
    
    if [ "$NVCC_MAJOR" -lt 11 ]; then
        GPU_ARCH="${GPU_ARCH} --generate-code arch=compute_75,code=[sm_75,compute_75]"
        echo -e "\t including: CUDA 10.X - {50,52,53,60,61,62,70,72,75}"
    else
        GPU_ARCH="${GPU_ARCH} --generate-code arch=compute_75,code=sm_75"
        if [ "$NVCC_MINOR" -eq 0 ]; then
            GPU_ARCH="${GPU_ARCH} --generate-code arch=compute_80,code=[sm_80,compute_80]"
            echo -e "\t including: CUDA 11.0 - {50,52,53,60,61,62,70,72,75,80}"
        else
            GPU_ARCH="${GPU_ARCH} --generate-code arch=compute_80,code=sm_80 \
                --generate-code arch=compute_86,code=[sm_86,compute_86]"
            echo -e "\t including: CUDA 11.1+ - {50,52,53,60,61,62,70,72,75,80,86}"
        fi
    fi
}
```

**Comment by leyojoseph** [comment]
Thanks for the reply.
Please note that I am running this on windows, not Linux. For some reason, our IT is not allowing to install WSL option.
I installed cusignal  withe the below command==>
# or, for CUDA 11.0
conda install -c rapidsai -c nvidia -c numba -c conda-forge \
    cusignal=0.17 python=3.8 cudatoolkit=11.0

 ****_Below lines shows where the cusignal error happens==>_****

filtered = cusignal.convolve(sig, win, mode='same') / cp.sum(win)
Traceback (most recent call last):

  File "<ipython-input-7-7d0d70fdd680>", line 1, in <module>
    filtered = cusignal.convolve(sig, win, mode='same') / cp.sum(win)

  File "C:\Users\ljoseph\AppData\Local\Continuum\anaconda3\lib\site-packages\cusignal\convolution\convolve.py", line 155, in convolve
    return _convolution_cuda._convolve(

  File "C:\Users\ljoseph\AppData\Local\Continuum\anaconda3\lib\site-packages\cusignal\convolution\_convolution_cuda.py", line 440, in _convolve
    out = _convolve_gpu(

  File "C:\Users\ljoseph\AppData\Local\Continuum\anaconda3\lib\site-packages\cusignal\convolution\_convolution_cuda.py", line 248, in _convolve_gpu
    _populate_kernel_cache(out.dtype, k_type)

  File "C:\Users\ljoseph\AppData\Local\Continuum\anaconda3\lib\site-packages\cusignal\convolution\_convolution_cuda.py", line 196, in _populate_kernel_cache
    _cupy_kernel_cache[(str(np_type), k_type)] = _get_function(

  File "C:\Users\ljoseph\AppData\Local\Continuum\anaconda3\lib\site-packages\cusignal\utils\helper_tools.py", line 57, in _get_function
    return module.get_function(func)

  File "cupy\core\raw.pyx", line 464, in cupy.core.raw.RawModule.get_function

  File "cupy\core\raw.pyx", line 89, in cupy.core.raw.RawKernel.kernel.__get__

  File "cupy\core\raw.pyx", line 106, in cupy.core.raw.RawKernel._kernel

  File "cupy\_util.pyx", line 59, in cupy._util.memoize.decorator.ret

  File "cupy\core\raw.pyx", line 533, in cupy.core.raw._get_raw_module

  File "cupy\cuda\function.pyx", line 239, in cupy.cuda.function.Module.load_file

  File "cupy_backends\cuda\api\driver.pyx", line 237, in cupy_backends.cuda.api.driver.moduleLoad

  File "cupy_backends\cuda\api\driver.pyx", line 124, in cupy_backends.cuda.api.driver.check_status

CUDADriverError: CUDA_ERROR_NO_BINARY_FOR_GPU: no kernel image is available for execution on the device

Appreciate if you can help me work on the windows platform with Tesla K40C. I cannot afford to buy anothe GPU at this point.

**Comment by awthomp** [comment]
Unfortunately, I believe WSL is a hard requirement to build our custom CUDA kernels.

Another option is to try cuSignal in a free GPU instance offered on Google Colab: https://colab.research.google.com/drive/1rY7Ln6rEE1pOlfSHCYOVaqt8OvDO35J0#forceEdit=true&offline=true&sandboxMode=true

**Comment by leyojoseph** [comment]
Thanks..let me try the option you suggested.
Is there a way to select which gpu to use(If PC has more  than one GPU) in cusignal. For example, nuba.cuda has this option as shown below==>

from numba import cuda
cuda.select_device(0)

Also is it possible to see on which GPU cusignal is running?

**Comment by awthomp** [comment]
You can use that or cupy's set device function. I always look at GPU usage with `watch nvidia-smi`. There are also some nice Jupyter plugins too.

https://medium.com/rapids-ai/gpu-dashboards-in-jupyter-lab-757b17aae1d5

**Comment by leyojoseph** [comment]
Hello,
An update.. I tried the code as below and is working. I am setting the gpu as device(1) which is Maxwell based Quadro K620.
import numpy as np
import cupy as cp
import cusignal as cu
import numba.cuda as cuu
**### cp.cuda.Device(1).use()**
start = 0
stop = 10
num_samps = int(1e7)
resample_up = 2
resample_down = 3

# Generate Data on CPU
cx = np.linspace(start, stop, num_samps, endpoint=False) 
cy = np.cos(-cx**2/6.0)

# %%time
gf = cu.resample_poly(cp.asarray(cy), resample_up, resample_down, window=('kaiser', 0.5))

But when I make the gpu device as (cp.cuda.Device(0)).use()  Tesla K40 (Kepler) with CC of 3.5, code is  giving the below error
CUDADriverError: CUDA_ERROR_NO_BINARY_FOR_GPU: no kernel image is available for execution on the device

### **In programs with Cusiganl where the GPU device is not specified as above, will it always use Device(0)?**

**Comment by mnicely** [comment]
@leyojoseph It looks like there's not SASS for CC3.5. 
Please refer to https://github.com/rapidsai/cusignal/issues/355#issuecomment-825667739

**Comment by leyojoseph** [comment]
Hello,
Curious to know your answer on my below question:

**In programs with Cusiganl where the GPU device is not specified as above, will it always use Device(0)?**

**Comment by leofang** [comment]
I think CUDA sets device 0 (dictated by CUDA_VISIBLE_DEVICES) as the default.

**Comment by awthomp** [comment]
We are closing this due to our perceived resolution and clarification of the issue. Please re-open if you have more information to add!
