### ISSUE TITLE
[QST] Building on WSL??

### ISSUE THREAD

**Issue by znmeb** [rapidsai/cusignal#356]
**What is your question?**

I'm looking at running cuSignal on a Windows machine using WSL 2 / Ubuntu 18.04. I looked at `conda/environments/cusignal_base.yml` and it calls for `cudatoolkit>=9.2,<=10.2`. 

It looks like the WSL install instructions give me CUDA 11.2:

```
❯ ll /usr/local/
total 36
drwxr-xr-x  2 root root 4096 May 21  2019 games/
drwxr-xr-x  2 root root 4096 May 21  2019 src/
drwxr-xr-x  2 root root 4096 May 21  2019 sbin/
drwxr-xr-x  2 root root 4096 May 21  2019 include/
lrwxrwxrwx  1 root root    9 May 21  2019 man -> share/man/
drwxr-xr-x  2 root root 4096 May 21  2019 etc/
drwxr-xr-x  6 root root 4096 Apr 21 18:47 share/
drwxr-xr-x  5 root root 4096 Apr 21 18:58 lib/
drwxr-xr-x 15 root root 4096 Apr 21 19:09 cuda-11.2/
drwxr-xr-x  2 root root 4096 Apr 21 19:09 bin/
lrwxrwxrwx  1 root root   22 Apr 21 19:09 cuda -> /etc/alternatives/cuda/
lrwxrwxrwx  1 root root   25 Apr 21 19:09 cuda-11 -> /etc/alternatives/cuda-11/
```

Is this going to break? I'm planning to try it with the upper constraint set to 11.2 to see what happens. If it works, do you want a pull request with another environment file for WSL / 11.2?

**Comment by awthomp** [comment]
Hey @znmeb -- Thanks for letting me know that the cusignal environment needs updated! That said, these ymls aren't used when building cusignal packaging via CI/CD. 

We've actually tested and successfully installed cusignal on WSL following the instructions posted here: https://github.com/rapidsai/cusignal#source-windows-os

Basically, don't worry about conda installing the cudatoolkit but simply conda or pip install:
- numpy
- numba
- scipy
- cupy

And then run `./build.sh` from the cusignal source.

**Comment by znmeb** [comment]
Thanks!!
