### ISSUE TITLE
ISTFT [FEA]

### ISSUE THREAD

**Issue by timsainb** [rapidsai/cusignal#358]
ISTFT is mentioned in the documentation under STFT, but hasn't been implemented. Are there plans to add ISTFT? 

Thanks,
TIm

**Comment by awthomp** [comment]
Hi @timsainb -- thanks for the hat tip. We missed porting ISTFT to GPU and will prioritize it for future releases. Do you have a general test case you'd like to cover here?

We also welcome your help if you'd like to help code it up!

**Comment by timsainb** [comment]
Thanks @awthomp! No real test case at the moment, I was considering adding this as a backend to speed up my noisereduce package + some other tools I've been working on.
