### ISSUE TITLE
[BUG] firwin function argument ignored

### ISSUE THREAD

**Issue by DuncanFyfe** [rapidsai/cusignal#399]
**Describe the bug**

The function [firwin](https://github.com/rapidsai/cusignal/blob/main/python/cusignal/filter_design/fir_filter_design.py#L140) appears to be missing a call to `_get_fs(fs, nyq)` near the top.  Because of this, when the `fs` argument is passed it ignored but the deprecated and incorrect default `nyq` value is used in the `cutoff` validations (Line 280+).

**Steps/Code to reproduce bug**

The following call will fail:
`cusignal.firwin( 984, cutoff=[1e6, 73e6], pass_zero=False, fs=245760000)`
with:
>  ValueError: Invalid cutoff frequency: frequencies must be greater than 0 and less than nyq.

while
`cusignal.firwin( 984, cutoff=[1e6, 73e6], pass_zero=False, nyq=122880000)`
will succeed.

**Expected behavior**

The call:
`cusignal.firwin( 984, cutoff=[1e6, 73e6], pass_zero=False, fs=245760000)`
Should return an ndarray of FIR filter coefficients.

**Environment details (please complete the following information):**

 - Environment location: Bare-metal
 - Method of cuSignal install: conda
 
**Additional context**
See [firwin2](https://github.com/rapidsai/cusignal/blob/main/python/cusignal/filter_design/fir_filter_design.py#L450) for an example where `_get_fs(fs, nyq)` is used.

**Comment by awthomp** [comment]
Thanks for letting us know, @DuncanFyfe. I've been out of pocket all week with vacation and will take a closer look tomorrow into Friday.

**Comment by awthomp** [comment]
@DuncanFyfe -- I've fixed this bug with https://github.com/rapidsai/cusignal/pull/400. We'll get this merged ASAP! Thanks for the report.

**Comment by DuncanFyfe** [comment]
Thanks, much appreciated.
