### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by eldaromer** [rapidsai/cusignal#419]
**Describe the bug**
Cross correlation function removes imaginary part

**Steps/Code to reproduce bug**
Simply try and correlate two complex vectors, you get this warning: ComplexWarning: Casting complex values to real discards the imaginary part
  return np.asarray(x, float)

**Expected behavior**
Cross correlating two complex vectors should take the complex conjugate of one, and work without stripping the imaginary component

**Environment details (please complete the following information):**
 - Environment location: Bare-metal, Jetson Nano
 - Method of cuSignal install: conda\

**Comment by awthomp** [comment]
Hi, @eldaromer. I noticed you closed the bug report. Are you seeing the correct behavior now?

**Comment by eldaromer** [comment]
Yes, it was a user error, sorry about that

**Comment by awthomp** [comment]
No worries! Thanks for using cusignal :).
