### ISSUE TITLE
[BUG] Jetson Nano Installation

### ISSUE THREAD

**Issue by yuvalg1987** [rapidsai/cusignal#421]
Hi,

I'm trying to install cusignal on the Jetson Nano (cuda version is 10.2) but the CuPy installation fails (after roughly an hour of compilation). I followed the instructions on the main page (including setting the `CUPY_NVCC_GENERATE_CODE` environment variable) but not luck. 

It's a bit hard to pin-point the exact issue so the compilation output is attached. I see some errors during the compilation of NCCL (not sure why it is being compiled at all as it's not supported on the Jetson) and cuGraph (is it a dependency?). In general. 

I understand that this is probably a CuPy issue but looking at both repos it seems that the cusignal community has more experience using CuPy on the Jetson platform.

Thanks
Yuval
[cusignal_compilation_output.txt](https://github.com/rapidsai/cusignal/files/7153550/cusignal_compilation_output.txt)

**Comment by awthomp** [comment]
Hi @yuvalg1987 -- We'll take a look. One quick question before I start digging in -- what version of JetPack are you running on your Jetson?

You can typically find this info via: `cat /etc/nv_tegra_release`

**Comment by yuvalg1987** [comment]
Thanks for the quick response! I'm using the latest Jetpack available for the Nano (version 4.6 with Cuda 10.2)

**Comment by awthomp** [comment]
> Thanks for the quick response! I'm using the latest Jetpack available for the Nano so version 4.6 with Cuda 10.2 and release #32

Great! Thanks! I'll try to reproduce your issue on my nano over the next couple of days. Thanks for the bug submission, and for using cusignal!

**Comment by yuvalg1987** [comment]
Thanks! I will continue and try and build this too (it takes forever ..), currently I'm trying to build it from source as well as using pip. One thing I noticed is that once it fails during the compilation it "restarts" again (or at least it seems like it from the verbose). I can see some configuration stuff running on the screen ... Any idea what is happening? 

In addition, I'm not sure how to manually disable the NCCL options of the build, since I see that the compiler is searching for those files. Any suggestions?

**Comment by awthomp** [comment]
Hmmm... nccl shouldn't be built, as that's a multi-GPU library. 

Let's start over and try again.

1. Deactivate current conda environment
```
conda deactivate cusignal-dev
```

2. Remove conda environment and clean up files
```
conda remove --name cusignal-dev --all
conda clean -a
```

3. Create new conda environment and activate it
```
conda create --name cusignal-dev
conda activate cusignal-dev
```

4. Download dependencies available via conda
```
conda install numpy numba scipy cudatoolkit pip
```

5. Pip install CuPy, and let the dependency solver find which version
```
pip install cupy
```

6. Go to cloned cusignal repo and run `./build.sh` to install cusignal.

**Comment by yuvalg1987** [comment]
As far as I see CUDA is already installed as part of the Jetpack and I verified it using the `nvcc -V` command, In addition, <conda install cudatoolkit>  doesn't work as there is no compatible version in the available channels. I found an old post written by you [https://github.com/rapidsai/cusignal/issues/8] saying that's OK and I can move forward with my current version so I will. 

The selected CuPy version that pip chose is 9.4, I'll update once this is finished. 
What about the <CUPY_NVCC_GENERATE_CODE> variable? currently it is set to the Nano's architecture (53). I'm assuming that's also Ok right?

**Comment by yuvalg1987** [comment]
I managed to compile it on a fresh image of the Jetson Nano so I assume that I might have done something wrong in the process. Thanks for all the help!

**Comment by awthomp** [comment]
Great! Happy to hear you're up and running, @yuvalg1987. Sometimes, a fresh install and a conda clean does the trick :). I'm going to close this issue, but feel free to re-open it if you hit another roadblock.

**Comment by gaosiy** [comment]
> I managed to compile it on a fresh image of the Jetson Nano so I assume that I might have done something wrong in the process. Thanks for all the help!

Hi, can you tell the image version you used to install cusignal? Thanks a lot.
