### ISSUE TITLE
Documentation of FIR filters incomplete

### ISSUE THREAD

**Issue by ChristophWiesmeyr** [rapidsai/cusignal#422]
For FIR filters the function signature seems to be missing in the documentation.

**Comment by awthomp** [comment]
Hey @ChristophWiesmeyr -- thanks for opening an issue and using cusignal. Could you please provide more information? What's missing? Are you talking about the online docs or the code? What function signatures are missing and where? Thanks for the help!

**Comment by ChristophWiesmeyr** [comment]
Hi, thanks for the response and sorry for the incomplete issue. I was referring to the docs, there I see all the parameters that go into the function but not the function itself:

![grafik](https://user-images.githubusercontent.com/8068536/135216999-15ac9594-f854-43c8-822e-62b203b8d613.png)

For other functions the function signature is there including all the defaults, see e.g.:

![grafik](https://user-images.githubusercontent.com/8068536/135217192-a6bb5489-6221-495c-8dbf-1ae36fe0cf1c.png)

I hope this helps.

**Comment by awthomp** [comment]
Ok great! Yes, it does. Thanks for the heads up.
