### ISSUE TITLE
[FEA] `decimate`: cache filter / allow input

### ISSUE THREAD

**Issue by OverLordGoldDragon** [rapidsai/cusignal#456]
Filter sampling takes by far the most time. Caching the filter or allowing the user to pass it would tremendously speed up recomputation with identical parameters.

**Comment by awthomp** [comment]
Okay! More info, @OverLordGoldDragon.

You can pass in your filter via the `n` parameter in `cusignal.decimate`. We correctly handle this input as either being the order of the filter or an array of arbitrary filter coefficients.

For example, expanding on the current code:
```python
import cupy as cp
import cusignal

x = cp.random.randn(10_000)
n = cusignal.firwin(41, 1.0 / 2, window='hamming')

# The following are equivalent
y = cusignal.decimate(x, 2)
yy = cusignal.decimate(x, 2, n=n)
```

I'm going to close this issue, but please let me know if this isn't what you're looking for. Happy to reopen it!
