### ISSUE TITLE
[DOC] A list of minor errors in the example codes

### ISSUE THREAD

**Issue by sosae0** [rapidsai/cusignal#457]
## Report incorrect documentation

**Location of incorrect documentation**
They are listed below with each link as well

**ISSUE 1.** Convolution of a 2nd order filter on a 1d signal: https://github.com/rapidsai/cusignal/blob/c620d8283fb7906d241d4c1bbc1940025d86e030/python/cusignal/convolution/convolve.py#L597
``` python
import cusignal as cs
import numpy as np
d = 50
a = np.random.uniform(-1,1,(200))
b = np.random.uniform(-1,1,(d,d))
c = cs.convolve1d3o(a,b)
```

**Describe the problems or issues found in the documentation**
The above code outputs an error because `c` should be `cs.convolve1d2o(a,b)` since this is a 2d example and the dimensions do not match.

**ISSUE 2.** 2D convolution with a complex Scharr operator: https://github.com/rapidsai/cusignal/blob/c620d8283fb7906d241d4c1bbc1940025d86e030/python/cusignal/convolution/convolve.py#L397
``` python
import cusignal
import cupy as cp
from scipy import misc
ascent = cp.asarray(misc.ascent())
scharr = cp.array([[ -3-3j, 0-10j,  +3 -3j],[-10+0j, 0+ 0j, +10 +0j],
                   [ -3+3j, 0+10j,  +3 +3j]]) # Gx + j*Gy
grad = cusignal.convolve2d(ascent, scharr, boundary='symm',                 mode='same')
import matplotlib.pyplot as plt
fig, (ax_orig, ax_mag, ax_ang) = plt.subplots(3, 1, figsize=(6, 15))
ax_orig.imshow(cp.asnumpy(ascent), cmap='gray')
ax_orig.set_title('Original')
ax_orig.set_axis_off()
ax_mag.imshow(cp.asnumpy(cp.absolute(grad)), cmap='gray')
ax_mag.set_title('Gradient magnitude')
ax_mag.set_axis_off()
ax_ang.imshow(cp.asarray(cp.angle(grad)), cmap='hsv')
ax_ang.set_title('Gradient orientation')
ax_ang.set_axis_off()
fig.show()
```
**Describe the problems or issues found in the documentation**
The above code outputs an error for the Gradient orientation image because 
```python 
ax_ang.imshow(cp.asarray(cp.angle(grad)), cmap='hsv')
``` 
was used instead of 
```python 
ax_ang.imshow(cp.asnumpy(cp.angle(grad)), cmap='hsv')
```

**ISSUE 3.** Example of Autocorrelation of white noise is an impulse:
https://github.com/rapidsai/cusignal/blob/c620d8283fb7906d241d4c1bbc1940025d86e030/python/cusignal/convolution/convolve.py#L222
```python
import cusignal
import cupy as cp
import numpy as np
sig = cp.random.randn(1000)
autocorr = cusignal.fftconvolve(sig, sig[::-1], mode='full')
```
```python
import matplotlib.pyplot as plt
fig, (ax_orig, ax_mag) = plt.subplots(2, 1)
ax_orig.plot(cp.asnumpy(sig))
ax_orig.set_title('White noise')
ax_mag.plot(np.arange(-len(sig)+1,len(sig)), autocorr)
ax_mag.set_title('Autocorrelation')
fig.tight_layout()
fig.show()
```
**Describe the problems or issues found in the documentation**
The above code outputs an error because the cupy arrays were not converted to numpy arrays.
```python 
ax_mag.plot(np.arange(-len(sig)+1,len(sig)), autocorr)
``` 
was used instead of 
```python 
ax_mag.plot(cp.asnumpy(cp.arange(-len(sig)+1,len(sig))), cp.asnumpy(autocorr))
```

**ISSUE 4.**Gaussian blur implemented using FFT convolution:
https://github.com/rapidsai/cusignal/blob/c620d8283fb7906d241d4c1bbc1940025d86e030/python/cusignal/convolution/convolve.py#L235
```python
from scipy import misc
face = misc.face(gray=True)
kernel = cp.outer(cusignal.gaussian(70, 8), cusignal.gaussian(70, 8))
blurred = cusignal.fftconvolve(face, kernel, mode='same')
```
```python
fig, (ax_orig, ax_kernel, ax_blurred) = plt.subplots(3, 1,figsize=(6, 15))
ax_orig.imshow(face, cmap='gray')
ax_orig.set_title('Original')
ax_orig.set_axis_off()
ax_kernel.imshow(cp.asnumpy(kernel), cmap='gray')
ax_kernel.set_title('Gaussian kernel')
ax_kernel.set_axis_off()
ax_blurred.imshow(cp.asnumpy(blurred), cmap='gray')
ax_blurred.set_title('Blurred')
ax_blurred.set_axis_off()
fig.show()
```
**Describe the problems or issues found in the documentation**
The above code outputs an error because the cupy arrays were not converted to numpy arrays.
```python 
blurred = cusignal.fftconvolve(face, kernel, mode='same')
``` 
was used. I tried
```python 
blurred = cusignal.convolve(face, kernel, mode='same')
``` 
and this fixed the issue even though the error was 
```python
TypeError: Argument 'a' has incorrect type (expected cupy._core.core.ndarray, got numpy.ndarray)
```
The `cusignal.colvolve` is similar to the implementation found in the scipy `signal.colvolve` API.

**ISSUE 5** argrelextrema outputs wrong arrays in example code: https://github.com/rapidsai/cusignal/blob/c620d8283fb7906d241d4c1bbc1940025d86e030/python/cusignal/peak_finding/peak_finding.py#L214-L224

```python
from cusignal import argrelextrema
import cupy as cp
x = cp.array([2, 1, 2, 3, 2, 0, 1, 0])
argrelextrema(x, cp.greater)
```
```python
y = cp.array([[1, 2, 1, 2],[2, 2, 0, 0],[5, 3, 4, 4]])
argrelextrema(y, cp.less, axis=1)
```

**Describe the problems or issues found in the documentation**
The above codes should output.
```python 
(array([3, 6]),)
``` 
and 
```python 
(array([0, 2]), array([2, 1]))
``` 
respectively, and not `(array([0, 3, 6]),)` and `(array([0, 0, 2]), array([0, 2, 1]))` as seen in the documentation

**ISSUE 6** argrelmax outputs wrong arrays in example code: https://github.com/rapidsai/cusignal/blob/c620d8283fb7906d241d4c1bbc1940025d86e030/python/cusignal/peak_finding/peak_finding.py#L168-L179

```python
from cusignal import argrelmax
import cupy as cp
x = cp.array([2, 1, 2, 3, 2, 0, 1, 0])
argrelmax(x)
```
```python
y = cp.array([[1, 2, 1, 2],[2, 2, 0, 0],[5, 3, 4, 4]])
argrelmax(y, axis=1)
```

**Describe the problems or issues found in the documentation**
The above codes should output.
```python 
(array([3, 6]),)
``` 
and 
```python 
(array([0]), array([1]))
``` 
respectively, and not `(array([0, 3, 6]),)` and `(array([0, 0, 2]), array([1 ,3, 0]))` as seen in the documentation.

Also on a side note, in this line https://github.com/rapidsai/cusignal/blob/c620d8283fb7906d241d4c1bbc1940025d86e030/python/cusignal/peak_finding/peak_finding.py#L160, `np.greater` was referenced instead of `cp.greater`

**ISSUE 7** argrelin outputs wrong arrays in example code: https://github.com/rapidsai/cusignal/blob/c620d8283fb7906d241d4c1bbc1940025d86e030/python/cusignal/peak_finding/peak_finding.py#L116-L127

```python
from cusignal import argrelmin
import cupy as cp
x = cp.array([2, 1, 2, 3, 2, 0, 1, 0])
argrelmin(x)
```
```python
y = cp.array([[1, 2, 1, 2],[2, 2, 0, 0],[5, 3, 4, 4]])
argrelmin(y, axis=1)
```

**Describe the problems or issues found in the documentation**
The above codes should output.
```python 
(array([1, 5]),)
``` 
and 
```python 
(array([0, 2]), array([2, 1]))
``` 
respectively, and not `(array([1, 5, 7]),)` and `(array([0, 0, 2]), array([0, 2, 1]))` as seen in the documentation.

**ISSUE 8** Waveform generation example code-plotting: https://github.com/rapidsai/cusignal/blob/c620d8283fb7906d241d4c1bbc1940025d86e030/python/cusignal/waveforms/waveforms.py#L71-L76

```python
import cusignal
import cupy as cp
import matplotlib.pyplot as plt
t = cp.linspace(0, 1, 500, endpoint=False)
plt.plot(t, cp.asnumpy(cusignal.square(2 * cp.pi * 5 * t)))
plt.ylim(-2, 2)
```
**Describe the problems or issues found in the documentation**
The above code outputs an error because the `t` cupy arrays were not converted to numpy array.
```python 
plt.plot(t, cp.asnumpy(cusignal.square(2 * cp.pi * 5 * t)))
``` 
was used instead of 
```python 
plt.plot(cp.asnumpy(t), cp.asnumpy(cusignal.square(2 * cp.pi * 5 * t)))
``` 

**Steps taken to verify documentation is incorrect**
I ran all the solution codes mentioned above and had no issues. These are minor changes I spotted a few months ago but I saw that the updated version (stable 22.02) and (nightly 22.04) still had the same errors.

**Suggested fix for documentation**
The fixes are highlighted under each issue mentioned above

---

**Comment by awthomp** [comment]
Great, @sosae0! The easiest way to contribute is to:

1. Fork the cusignal repo. You can do this via the "Fork" button on the main cusignal page.
2. Create a feature branch in your own fork via `git checkout -b <branch_name>`
3. Edit applicable code to fix the incorrect documentation
4. Commit changes and push to your own branch, e.g. `git commit -m "fixing docs"` then `git push origin <branch_name>`
5. Once complete, open a PR on the cuSignal program. GitHub should be smart enough to do most of this for you :).

**Comment by sosae0** [comment]
Sounds great @awthomp. Will get on it when I get a chance. Thanks for the additional info.

**Comment by sosae0** [comment]
Hi @awthomp, I just created the pull request for this issue.

**Comment by awthomp** [comment]
ok to test

**Comment by awthomp** [comment]
Thanks, @sosae0 -- I'll take a look and get it merged tomorrow!
