### ISSUE TITLE
[BUG]Jetson nano installation issue

### ISSUE THREAD

**Issue by gaosiy** [rapidsai/cusignal#464]
**Describe the bug**
When I install cusignal on jetson nano, I was stuck at :
`conda env create -f conda/environments/cusignal_jetson_base.yml`
It cost one night and let jetson nano dead.
![image](https://user-images.githubusercontent.com/16640004/159627374-447bf1ad-f765-4fb4-b696-eb1fa1781116.png)

I search the Issues and find the same question
[BUG] Jetson Nano Installation #421
At that topic, the author refresh the image and solve the problem, but that did not work to me.
I try below step
![image](https://user-images.githubusercontent.com/16640004/159627611-8418f60a-1ee1-4d64-a2d9-74fdfbfe2024.png)
and been stuck at cupy installation.
What should I do next, please help me with that.

**Comment by awthomp** [comment]
Hey @gaosiy --thanks for the bug report, and sorry you're having problems building cusignal! How long has the `pip install cupy` hung for during install? It takes about ~30 minutes, IIRC. Also, can you confirm you're running on the lastest version of JetPack?

**Comment by gaosiy** [comment]
Thanks awthomp, I use two jetpack versions, 32.7.1 and 32.6.1, I get the same problem. Now I use the 32.6.1 version. When I install cupy, the longest time I use is more than 12 hours. During the conda create step, I found jetson nano system warning about memory, I think maybe the memory problem cause the stuck, so last night I try to install it again without any other app running, it seems no problem with 
`conda env create -f conda/environments/cusignal_jetson_base.yml
`
but when I use pytest -v to test, it show
![4ffcd91f51aefd12228fd0f0f0bc8ec](https://user-images.githubusercontent.com/16640004/159832158-327dfc39-c005-409c-83b7-54b216292f3a.jpg)
It still something wrong with cupy, So I run
`conda env update -f conda/environments/cusignal_jetson_base.yml
`
Now the system is stuck again, the system time even stuck at a value, I try more than 10 times.
Please help me with that, or can I use docker verison in jetson nano? I think that may be more easy.
Thanks.

**Comment by awthomp** [comment]
Try installing cupy with `pip install cupy-cuda102`

The cupy folks have recently built wheels for 10.2 (to support Jetson). This should avoid you having to build cupy from source. 

Let me know if this works.

**Comment by gaosiy** [comment]
Hi awthomp, after 90 minutes waiting, the stuck has gone, I found the command
`conda env update -f conda/environments/cusignal_jetson_base.yml`
rebuild the cupy and now I use 
`pytest -v `
it seems to work well and now the script is testing all operations of cusignal.
Thanks for your help!

**Comment by gaosiy** [comment]
![7a6b6b858050c46b1c7469d3bf0a724](https://user-images.githubusercontent.com/16640004/159838137-9ea73198-5c81-462a-ab51-dfb90a0e4804.jpg)

**Comment by awthomp** [comment]
Great news!! Some of the tests with cusignal will fail, as the default tests allocate arrays buffer than the Nano’s memory size, but you should be good to go. I’ll close this issue, but feel free to open it back up I’d you have more problems.
