### ISSUE TITLE
[FEA] support distance_transform_edt in scipy

### ISSUE THREAD

**Issue by EdwardZhao1991** [rapidsai/cusignal#467]
**Is your feature request related to a problem? Please describe.**

Would it be possible to support distance transform?

**Describe the solution you'd like**

Just like the one in scipy

https://docs.scipy.org/doc/scipy/reference/generated/scipy.ndimage.distance_transform_edt.html

**Comment by awthomp** [comment]
Hey @EdwardZhao1991 -- Thanks for the issue and for using cuSignal.

This might actually be a better feature for [cuCIM](https://github.com/rapidsai/cucim), which focuses on image processing via ndarrays and GPU accelerates much of `scipy.ndimage`.

CC @quasiben for his thoughts on where this feature request would be best.

Thanks!

**Comment by grlee77** [comment]
We have discussed it in the past for cuCIM and I hope to work on it in the near future. I think it should live in CuPy under cupyx.scipy.ndimage.

**Comment by awthomp** [comment]
Going to close this issue as we feel this feature would be best implemented in a separate library.
