### ISSUE TITLE
[FEA] Support for decimate function with FIR Filter

### ISSUE THREAD

**Issue by boonedoggle** [rapidsai/cusignal#47]
I would like the be able to use the `cusignal.decimate` function. I realize that IIR filters are difficult with GPUs but FIR filters should not have the same issue.

**Comment by awthomp** [comment]
The FIR case of `scipy.signal.decimate` makes use of the following functions -- all of which are currently implemented in cusignal 0.13:
* firwin
* upfirdn
* resample_poly

SciPy's version: https://github.com/scipy/scipy/blob/v1.4.1/scipy/signal/signaltools.py#L4154-L4245

This seems like a very easy issue to address. As @boonedoggle mentioned, the IIR case involves `lfilter` and `filtfilt` which strike on the data dependencies listed here: https://github.com/rapidsai/cusignal/issues/7

I'll start work this week and file a PR when ready.

Thanks for the bringing up the issue, @boonedoggle !
