### ISSUE TITLE
[FEA] Support for C++ API

### ISSUE THREAD

**Issue by NiclasEsser1** [rapidsai/cusignal#509]
Hi, the cuSignal library looks nice, and I would like to use it. However, I would appreciate it if the functionalities of cuSignal were also available in a C++ environment. I understand that cuSignal intends to bring scipy-functions to the GPU, but I see great potential to make the developed CUDA code available through a C++ API. Are there already efforts to create a C++-based library?

If not, I would be willing to work on C++ wrappers for the CUDA kernels.

Also, is there possibly an alternative library that already covers the functionality? Unfortunately, I could not find anything on the internet.

Cheers, Niclas

**Comment by beckernick** [comment]
Developing and maintaining a full C++ API for cuSignal would likely be a large effort and careful consideration. I'd recommend looking at our C++ header only library [MatX](https://github.com/nvidia/matx). [This functionality](https://nvidia.github.io/MatX/api/transformations.html) may be particularly relevant (I hope).

If a feature is in cuSignal but not MatX, please let us know by filing an issue!

cc @cliffburdick @luitjens @awthomp

**Comment by NiclasEsser1** [comment]
Thanks a lot! This is what I'm looking for.
