### ISSUE TITLE
[FEA] Implement IIR filtering

### ISSUE THREAD

**Issue by dicta** [rapidsai/cusignal#52]
This issue is an attempt to unblock https://github.com/rapidsai/cusignal/issues/7 with regard to IIR digital filtering. 

Problem: `scipy.signal` API implements types of filters that are suitable for CPU implementation, but contain data dependencies that prohibit GPU acceleration without changing the form of the filter implementation. Specifically, `scipy.signal.lfilter` uses a Direct Form II structure and `scipy.signal.sosfilt` uses a series of cascaded second-order sections. Note that these filter forms are (theoretically) equivalent and differ in the number of operations required and numerical stability. If we change the filter form, we should use a different function name in order to avoid surprising the API user.

Options:

- `scipy.signal.lfilter` contains data dependencies of arbitrary complexity when IIR coefficients are present. It would be reasonable to implement this for FIR filters only, which do not contain the data dependence. If IIR coefficients are specified, we can produce a warning that the user must use a different filter form. This is reasonable to ask the user to do as the `scipy.signal` module contains functions to convert filter coefficients between representations (see, for example, `scipy.signal.tf2sos`).

- `scipy.signal.sosfilt` implements a filter as a cascade of N second-order-sections. This can be parallelized on GPU by computing each filter in the cascade (for a block of samples) in a separate thread. Each time the kernel runs, another block of samples is processed and the outputs of thread K from the current block become the inputs to thread K+1 on the next block. This approach is summarized in a [presentation from GTC 2014](http://on-demand.gputechconf.com/gtc/2014/presentations/S4382-flexible-iir-filtering-for-audio-processing.pdf).

- We can take this idea one step further by using the parallel form of the filter. In contrast to `scipy.signal.sosfilt` which applies a series of filters to an input signal, the parallel form consists of a set of second-order filters that each operate on the input signal independently, and the filter outputs of each are summed in order to get the final result. [This page](http://home.mit.bme.hu/~bank/parconv/) is a good summary, with code examples, of the state of the art in converting filters to this form. At this point, the achieved speedup is that we can both process multichannel signals in parallel, if applicable, and reduce the cost of computing N second-order sections to that of single second-order section plus one parallel reduction. Since this is a different filter form with changed numerical properties, this should get a new function name if implemented.

Researchy extensions:

- We've now simplified the problem to "can we accelerate the computation of a single second-order section of an IIR on the GPU". The closest to state of the art here that I've been able to find has been in [this paper](https://doi.org/10.1109/ICASSP.1986.1169082) which describes how to decompose the filter into sets of blocks in order to break the data dependence at the cost of an increase in total FLOPS required.

**Comment by mnicely** [comment]
@dicta I've been trying to put this on the GPU, but I can't seem to get the math correct. 
When I look at the following code from `scipy.signal.sosfilt` I see a dependency with `x[i, n]`. 
Can you help me see what I'm missing?

```bash
for i in range(n_signals):
    for n in range(n_samples):
        for s in range(n_sections):
             x_n = x[i, n]  # make a temporary copy
             # Use direct II transposed structure:
             x[i, n] = b[s, 0] * x_n + zi[i, s, 0]
             zi[i, s, 0] = ( b[s, 1] * x_n - a[s, 0] * x[i, n] + zi[i, s, 1])
             zi[i, s, 1] = ( b[s, 2] * x_n - a[s, 1] * x[i, n])
```

Also, I agree with your comments on the parallel form. If we can get the cascade working, the parallel should be straight-forward.

**Comment by dicta** [comment]
The trick to placing the cascade on the GPU efficiently is that for a large number of sections, you can run the computations for a section on one set of samples in parallel with a different section on a different set of samples. And then you can unroll the computations of a section to process a block of samples instead of looping over a single sample in order to increase the amount of work done in each kernel function (this is probably a very significant optimization but we can write the initial version without this).

One of the big reasons we can gain efficiency here is that the underlying filter computation is identical across all threads, so the kernel launch is a determination of "for what values of N and S can we proceed in parallel?".

Here's one example (n_signals = 1 for simplicity, because this is trivially parallelizable):
- Processing n_samples = 6
- Filter has n_sections = 4

- Stage 1: startup
```
Iteration 1: Process (Sample 1, Section 1)
Iteration 2: Process (Sample 2, Section 1), (Sample 1, Section 2)
Iteration 3: Process (Sample 3, Section 1), (Sample 2, Section 2), (Sample 1, Section 3)
Iteration 4: Process (Sample 4, Section 1), (Sample 3, Section 2), (Sample 2, Section 3), (Sample 1, Section 4)
```
- Stage 2: Moving through the input samples
```
Iteration 5: Process (Sample 5, Section 1), (Sample 4, Section 2), (Sample 3, Section 3), (Sample 2, Section 4) 
Iteration 6: Process (Sample 6, Section 1), (Sample 5, Section 2), (Sample 4, Section 3), (Sample 3, Section 4) 
```

- Stage 3: finishing the filter
```
Iteration 7: Process (Sample 6, Section 2), (Sample 5, Section 3), (Sample 4, Section 4)
Iteration 8: Process (Sample 6, Section 3), (Sample 5, Section 4)
Iteration 9: Process (Sample 6, Section 4)
```

For n_samples much larger than n_sections (the expected case): this achieves a factor of up to `n_sections` speedup over the serial case.

**Comment by dicta** [comment]
Also as an implementation detail relative to the above comment, n_sections being on the order of a warp size is likely for many applications, so a stab at a fast implementation of the loop iterations would be to create a kernel that processes up to 32 sections (or other warp size, if different for particular hardware), using `_shfl_up()` instructions to implement the data access patterns between iterations in stages 1 and 2 of the algorithm.

**Comment by mnicely** [comment]
@dicta I was able to implement the workflow you described above and pushed it to Adam's [PR](https://github.com/rapidsai/cusignal/pull/99). The CuPy version is 53x faster than the CPU for our largest scenario. 

There are a few limitation. I'm using shared memory to move samples to the next sections. The limits the maximum number of sections to 1024, and a little less for double precision. Also, one signal is assigned to one block meaning your really don't take full advantage of the GPU unless you process 100s/1000s of signals.

This probably all we an get into the 0.14 release. Maybe sometime over the next two weeks we can go over 
>unroll the computations of a section to process a block of samples instead of looping over a single sample

I wasn't have to workout the math :confused:

**Comment by awthomp** [comment]
To pile on with @mnicely -- The thing that'd be the most helpful for us @dicta, at this point, would be if you pull this PR and see how it's performing for your given problem set. You're more than welcome to push to my fork, too.
