### ISSUE TITLE
[BUG] Correlate2d flips the second filter (actually implements conv2d)

### ISSUE THREAD

**Issue by OfekCohen1** [rapidsai/cusignal#538]
**Describe the bug**
Correlate2d flips the 2nd filter. This is due to the implementation using convolve2d, without flipping the 2nd array. See here:
https://github.com/rapidsai/cusignal/blob/6e1af8e944a5afe833e343a7350c5c16b98d9e72/python/cusignal/convolution/correlate.py#L246

**Steps/Code to reproduce bug**
```
import cusignal
import cupy as cp

first_array = cp.arrray([[1,1,1], [0,0,0]])
second_array = cp.array([[1,2,3,4,5]])

result = cusignal.correlate2d(first_array, second_array, 'full')

# You can see that the result will be flipped
print(result)
```

**Expected behavior**
Should expect to receive correlation2d, instead receives. convolve2d.  
This happens in `full` and `same`. In `valid` mode the result is correct, due to the flip at the end of the implementation
https://github.com/rapidsai/cusignal/blob/6e1af8e944a5afe833e343a7350c5c16b98d9e72/python/cusignal/convolution/correlate.py#L255

**Environment details (please complete the following information):**
installed cusignal from source (build.sh)

**Comment by awthomp** [comment]
Thanks for the bug report, @OfekCohen1! We will take a look._

**Comment by OfekCohen1** [comment]
My bad, made a mistake.
