### ISSUE TITLE
[BUG] Extremely slow import times on 0.14 branch

### ISSUE THREAD

**Issue by dicta** [rapidsai/cusignal#54]
Pre-compilation of specialized CUDA kernels currently occurs at module import time, which causes excessively long times to `import cusignal` (~10 seconds on Jetson TX2, not as bad on desktop). This issue is likely to get worse as more specialized numba/cupy kernels are implemented.

In general, we should provide a function for pre-compilation of specific parts of cusignal, and fall back to lazily compiling kernels on-demand if needed.

Since most signal processing code will only use a subset of cusignal functionality and often work only with a single data type, it would be nice to be able to do something like the following:

```
import cusignal
cusignal.precompile_kernels(module=cusignal.signaltools, dtype=numpy.float32, backend=cusignal.backends.numba)
```

Internally to cusignal, this would require functions that currently look up kernels in the kernel cache to do a few things:

1) Look up the required kernel in the cache
2) On failure, attempt to compile the kernel and store it in the cache
3) On failure, ensure the cache entry is empty and signal an unsupported operation to the user.

**Comment by mnicely** [comment]
@awthomp I think we can visit this after we restructure the codebase. Things should get simpler.

**Comment by awthomp** [comment]
@mnicely -- Let's file a separate issue for the codebase restructure and outline your proposal. I think we should work that off ASAP.

I just downloaded the cusignal-nightly release, and even the import on my workstation is relatively slow.

**Comment by gmarkall** [comment]
Rather than requiring the user to explicitly precompile the kernels, could the kernel cache for a given function and arguments be populated on the first use for a given type instead? This would be similar to Numba's caching mechanism (when types are not specified - when they are specified, like we are/were doing, it compiles everything up-front).

**Comment by mnicely** [comment]
@dicta @awthomp @gmarkall 
Please see PR https://github.com/rapidsai/cusignal/pull/56. I believe it solves our issues and meets everyone's suggestions.

**Comment by dicta** [comment]
```
from enum import Enum
import itertools

class GPUBackend(Enum):
    NUMBA = 1
    CUPY = 2

def _precompile_kernels(dtype=None, backend=None):
    r"""
    Precompile GPU kernels for later use.

    Parameters
    ----------
    dtype : numpy datatype or list of datatypes, optional
        Data types for which kernels should be precompiled. If not
        specified, all supported data types will be precompiled.
    backend : GPUBackend, optional
        Which GPU backend to precompile for. If not specified,
        all supported backends will be precompiled.
    """
    dtype = list(dtype) if dtype else _SUPPORTED_TYPES.keys()
    backend = list(backend) if backend else list(GPUBackend)
    for d, b in itertools.product(dtype, backend):
        _populate_kernel_cache(d, b)
```

Something like this is what I had in mind as implementation based on #56, just thinking about how we can make the API the most flexible (and avoid having to come back and change it later). Having an enumeration for numba/cupy selection also means if we add a third backend, we can support this without having to go look at every use_numba flag across the codebase. [Also, having a flag with the same name across a module that might have default values of true or false may be confusing].

**Comment by mnicely** [comment]
Fixed with https://github.com/rapidsai/cusignal/pull/56
