### ISSUE TITLE
[BUG] firwin parameter 'pass_zero' should accept string arguments, but doesn't

### ISSUE THREAD

**Issue by sevagh** [rapidsai/cusignal#553]
**Describe the bug**

In the firwin function documentation (https://docs.rapids.ai/api/cusignal/stable/api.html#id19), it says `pass_zero` can be a string:
>pass_zero{True, False, ‘bandpass’, ‘lowpass’, ‘highpass’, ‘bandstop’},
>    optional If True, the gain at the frequency 0 (i.e. the “DC gain”) is 1. If False, the DC gain is 0. Can also be a string argument for the desired filter type (equivalent to btype in IIR design functions).
>    New in version 1.3.0: Support for string arguments.

However, in the code (https://github.com/rapidsai/cusignal/blob/7772dad09d64bd5d0c152fa3b250d702327e3ecf/python/cusignal/filter_design/fir_filter_design.py#L310), it is used as a bool directly:
```
    pass_nyquist = bool(cutoff.size & 1) ^ pass_zero
```

**Steps/Code to reproduce bug**

Use the firwin function with `pass_zero='lowpass'` or another string argument:
```
b[0, :] = firwin(
    n_fir + 1, edge[0] / nyquist_freq, window="hann", pass_zero="lowpass"
)
File "/project/haaqi/eb.py", line 1548, in melcor9
    b[0, :] = firwin(
  File "/usr/local/lib/python3.8/dist-packages/cusignal-23.4.0a0+11.gab63007-py3.8.egg/cusignal/filter_design/fir_filter_design.py", line 310, in firwin
    pass_nyquist = bool(cutoff.size & 1) ^ pass_zero
TypeError: unsupported operand type(s) for ^: 'bool' and 'str'
```

**Expected behavior**

In the scipy signal code (https://github.com/scipy/scipy/blob/main/scipy/signal/_fir_filter_design.py#L417), there is a block that handles the string case of `pass_zero`:
```
   if isinstance(pass_zero, str):
        if pass_zero in ('bandstop', 'lowpass'):
            if pass_zero == 'lowpass':
                if cutoff.size != 1:
...
```

I would probably expect cuSignal to do the same (I'm trying to modify scipy.signal code to use cuSignal instead).

**Environment details (please complete the following information):**

Installed cuSignal from source in a nvcr.io/pytorch container (Python 3.8):
```
FROM nvcr.io/nvidia/pytorch:22.12-py3

RUN git clone https://github.com/rapidsai/cusignal /cusignal
WORKDIR /cusignal
RUN ./build.sh --allgpuarch
```

**Comment by awthomp** [comment]
Thanks for using cusignal, @sevagh. We'll take a look at your bug report and scope out the fix.
