### ISSUE TITLE
[FEA] Implement 1D Convolution/Correlation

### ISSUE THREAD

**Issue by awthomp** [rapidsai/cusignal#57]
cuSignal currently supports 2D convolution and correlation via the use of raw CuPy CUDA kernels. The 1D equivalent of these operations are house, on CPU, in `numpy.convolve` and `numpy.correlate` but [have yet to be implemented in CuPy](https://docs-cupy.chainer.org/en/stable/reference/comparison.html). Since we already have a framework for raw CUDA kernels within CuPy, I can see two paths:

1. Quickly implement 1D convolve/correlate within cuSignal using our raw CuPy CUDA kernel framework and then file an issue onto CuPy with our work as reference
2. Work off this PR under CuPy

I'm personally in favor of option 1 because I think it's the lowest learning curve and that we already basically understand the implementation.

CC @mnicely

**Comment by mnicely** [comment]
@awthomp Should be straightforward. In which file do you think the functions belong? Do you want the Numba complement kernel as well?

**Comment by awthomp** [comment]
@mnicely Let's go straight to raw CuPy kernels and place the initial code in the same file as `correlate2d` and `convolve2d`.

**Comment by mnicely** [comment]
@awthomp Sounds good. Notice my comment in https://github.com/rapidsai/cusignal/pull/56/ on how this will affect compile time.
