### ISSUE TITLE
[FEA] Add 2D+ functionality to lfilter

### ISSUE THREAD

**Issue by mnicely** [rapidsai/cusignal#79]
I've discovered my lfilter implementation doesn't work on input signals greater than 1D. 

NotImplementedError will be used until this feature is added. 

@luigifreitas It looks like there these two lines are not equivalent. It works for 1D only.

If you have time to track down the issue let me know. If not, I'm going to put this in the queue for later.

```python
for i_sample, o0 in enumerate(input_signal_windows.t()):
```

```python
for i, o0 in enumerate(input_signal_windows[0, :]):
```

**Comment by luigifreitas** [comment]
Hi @mnicely, thanks for reviewing the code. The `torch.t()` transposing method appears to be compatible with `numpy.ndarray.T`. The code below should enable operations with the input signal being greater than 1-D. I'm not in a CUDA enabled computer right now. I'm hoping to validate this code in the next couple of hours.
```
for i, o0 in enumerate(input_signal_windows.T):
```

**Comment by luigifreitas** [comment]
Just verified that the proposed solution above does work as expected.

**Comment by awthomp** [comment]
Closing due to `lfilter` deprecation in https://github.com/rapidsai/cusignal/pull/93
