### ISSUE TITLE
[FEA] Remove Numba 0.49 check.

### ISSUE THREAD

**Issue by mnicely** [rapidsai/cusignal#88]
# Info

The following files check Numba version.
1. upfirdn.py
2. signaltools.py

```python
try:
    # Numba <= 0.49
    from numba.types.scalars import Complex
except ImportError:
    # Numba >= 0.49
    from numba.core.types.scalars import Complex
```

Release 0.14 will require Numba 0.49 making this check obsolete.

**Comment by awthomp** [comment]
PR https://github.com/rapidsai/cusignal/pull/84 closes this issue.
