### ISSUE TITLE
[FEA] Added pytest-benchmark to yaml files

### ISSUE THREAD

**Issue by mnicely** [rapidsai/cusignal#94]
Hey @awthomp. What do you think about us added pytest-benchmark to the yaml files so it's installed by default. 

I think eventually we might want to add a benchmark step in the issue process. If a user thinks they are seeing performance issues, we can provide them a command to run and they can upload the results for analysis.

**Comment by awthomp** [comment]
@mnicely -- I was looking at what other RAPIDS libs do, and they use the conda/environments ymls as dev environments. I'm supportive of adding pytest-benchmarks here. I'd like to confirm, but I believe the Conda channel cusignal build is controlled by `conda/recipes/meta.yml`

**Comment by mnicely** [comment]
So you mean like adding a separate ‘cuSignal-dev.yml’? I like that.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by awthomp** [comment]
Yeah, and even more to the point: I thought our nightly edits were uploading to Anaconda Cloud via the Conda environments in `conda/environments`, but I *think* it's using `conda/recipes/cusignal`, meaning our ymls in environments are automatically dev envs. We can confirm this Monday and make appropriate changes (like changing the env name from cusignal to cusignal-dev).
